In [1]:
from DQNAgent import Experience, ExperienceReplay, Net, DQNAgent
import numpy as np
from time import sleep

In [2]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)

Discrete(2)


In [3]:
#Change hyperparameters here
agent = DQNAgent(layerSizes=[4, 64, 64, 2],
                epsilon=0.8, eps_decay=0.99997, batch_size=32, discount_fact=0.99, 
                 lr=0.15, num_actions=2, target_update_freq=10000, mem_size = 65000,
                    update_freq = 2)

In [4]:
action=0
i_episode = 0

#Arbitary condition, probably could make while(not converged) but this works for now
while agent.epsilon > 0.11:
    i_episode += 1
    state = env.reset()
    score = 0
    agent.loss_val = 0
    for t in range(1000):
#         env.render()
        action = agent.getAction(state)
        n_state, reward, done, info = env.step(action)
        score += reward
        agent.step(state, action, reward, n_state, int(done))
        
        state = n_state
        
        if done:
            print(agent.epsilon)
            print(agent.loss_val/t+1)
            print(n_state)
            print(f"{i_episode} Episode finished after {t+1} timesteps")
            break
env.close()

0.8
1.0
[-0.05507407 -0.7532116   0.21453209  1.5375613 ]
1 Episode finished after 18 timesteps
0.8
1.0
[-0.08581939 -1.3257807   0.22071913  2.2757778 ]
2 Episode finished after 9 timesteps
0.7994401819636052
1.0566727598056649
[-0.22340117 -0.8179757   0.21609257  1.4255818 ]
3 Episode finished after 34 timesteps
0.7990805058229445
1.001998126230319
[-0.06813703  0.17409109  0.21864428  0.2555923 ]
4 Episode finished after 17 timesteps
0.798082254271373
1.0010274169070181
[-0.71813494 -2.1368914   0.23624882  1.9683211 ]
5 Episode finished after 51 timesteps
0.797643418751375
1.001636097492883
[-0.191033   -0.6335081   0.21302578  1.2259411 ]
6 Episode finished after 21 timesteps
0.7969258446917623
1.0006546476975524
[-0.06349622  0.11423605  0.21303701  0.603918  ]
7 Episode finished after 37 timesteps
0.7964079982647658
1.000306019791169
[-0.01105236 -0.4320005   0.21594428  1.3616835 ]
8 Episode finished after 26 timesteps


C:\Python39\lib\site-packages\torch\nn\modules\loss.py:921: UserWarning: Using a target size (torch.Size([32, 32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)


0.7960496863339049
1.0002294649157728
[ 0.11699703  0.35568243 -0.21035272 -0.9036066 ]
9 Episode finished after 18 timesteps
0.795771110732814
1.0002989202572887
[-0.11078033 -0.63053447  0.22691512  1.1515315 ]
10 Episode finished after 13 timesteps
0.7951744912444283
1.000222086578764
[0.0173044  0.02017988 0.21326368 0.67630523]
11 Episode finished after 30 timesteps
0.7941811192826915
1.000146253584535
[ 0.34721762  1.0037194  -0.21798474 -1.1645982 ]
12 Episode finished after 51 timesteps
0.7933873152862938
1.0001350108635587
[ 0.04843445  1.150423   -0.22986627 -2.0909963 ]
13 Episode finished after 40 timesteps
0.793149328841749
1.0001440481137251
[ 0.09399601  1.0256766  -0.23130886 -1.8149046 ]
14 Episode finished after 11 timesteps
0.7923565561458387
1.0002658285076718
[ 0.06542947  0.40684035 -0.2130492  -1.3964978 ]
15 Episode finished after 40 timesteps
0.7918812729291957
1.0001912322521727
[ 0.21638064  1.1729865  -0.2285524  -1.9996336 ]
16 Episode finished after 24 tim

0.7704777582023161
1.0002991781996873
[ 0.20656958  1.369244   -0.23646413 -2.1769416 ]
76 Episode finished after 19 timesteps
0.770208131433657
1.0001791998790093
[-0.23593    -1.4220629   0.24138647  2.2578118 ]
77 Episode finished after 13 timesteps
0.7700155986550391
1.000295708506019
[ 0.14970578  1.7433562  -0.22350499 -2.793257  ]
78 Episode finished after 11 timesteps
0.7696306774709172
1.000335152548934
[ 0.09886935  0.788505   -0.20970619 -1.5599651 ]
79 Episode finished after 20 timesteps
0.7692459487040897
1.0002961579210885
[ 0.18556677  1.1482178  -0.24554501 -2.193051  ]
80 Episode finished after 20 timesteps
0.7688998572512319
1.0002572251432866
[ 0.05437071  0.9991079  -0.21169668 -1.8270686 ]
81 Episode finished after 17 timesteps
0.7686307826650726
1.000249463154782
[ 0.14547423  1.1960808  -0.24008521 -1.9807354 ]
82 Episode finished after 14 timesteps
0.7683618022408932
1.000188053209318
[ 0.12372513  0.9414089  -0.23313484 -1.8779258 ]
83 Episode finished after 15

0.7466600560299228
1.0002796879747289
[-0.1267182  -1.1526015   0.23998459  1.9955761 ]
151 Episode finished after 12 timesteps
0.7462868099899653
1.0003257952792208
[ 0.19651575  0.9648814  -0.24458683 -1.5892823 ]
152 Episode finished after 19 timesteps
0.7460629519308581
1.0002606101843412
[-0.13944753 -1.3866042   0.21748964  2.1531317 ]
153 Episode finished after 13 timesteps
0.7458764548435167
1.000317575510255
[ 0.06943101  0.81285816 -0.23565193 -1.5206718 ]
154 Episode finished after 10 timesteps
0.7456154372395724
1.0002856580346513
[ 0.22463122  1.343692   -0.22342663 -2.1142797 ]
155 Episode finished after 13 timesteps
0.7453917805671154
1.000245775008807
[ 0.16933496  1.3791353  -0.22697031 -2.3043587 ]
156 Episode finished after 13 timesteps
0.745242713391506
1.0002349134717536
[-0.08528446 -1.1315613   0.21266188  2.0029576 ]
157 Episode finished after 8 timesteps
0.7449819175638013
1.000272888877729
[-0.04771285 -1.1795355   0.22577988  2.1170297 ]
158 Episode finished 

0.7272420340839622
1.000237916581682
[ 0.15965718  0.9621692  -0.24197729 -1.6619008 ]
219 Episode finished after 11 timesteps
0.7267694685480086
1.000283756518911
[ 0.14207654  0.9561502  -0.22006892 -1.8973991 ]
220 Episode finished after 25 timesteps
0.7265514649594824
1.0002430626336718
[ 0.1454341   0.8033932  -0.22762465 -1.4410377 ]
221 Episode finished after 12 timesteps
0.7262608952270155
1.0003842437145067
[ 0.11561049  1.1676186  -0.22779629 -2.1505945 ]
222 Episode finished after 16 timesteps
0.7260793481588234
1.000191261139763
[ 0.16528757  0.44116318 -0.21281317 -0.896713  ]
223 Episode finished after 10 timesteps
0.7258615515805361
1.00038230190297
[-0.18017507 -1.2033044   0.21407497  1.995685  ]
224 Episode finished after 12 timesteps
0.7256801043382725
1.0001472024494433
[ 0.05330792  0.59828603 -0.20962945 -1.2410402 ]
225 Episode finished after 11 timesteps
0.725281080046935
1.000247346197284
[-0.1441956  -1.008864    0.23236293  1.6331519 ]
226 Episode finished af

0.7091086172181388
1.0002782480625778
[ 0.11153968  0.84311724 -0.23142833 -1.8360624 ]
284 Episode finished after 20 timesteps
0.7088604664272127
1.00025731659116
[-0.1354292 -1.3536856  0.2275995  2.366521 ]
285 Episode finished after 15 timesteps
0.7086478348677799
1.0002393222006503
[-0.14844953 -1.8134123   0.25740966  2.9043455 ]
286 Episode finished after 11 timesteps
0.7082227630742665
1.000189732153861
[-0.00286193  0.6146647  -0.23719525 -1.8913887 ]
287 Episode finished after 25 timesteps
0.707939523539673
1.0001633013749338
[-0.13665152 -0.97391057  0.2291895   1.8498452 ]
288 Episode finished after 15 timesteps
0.7077625563563913
1.000288328419265
[ 0.13980573  1.0222466  -0.2349197  -1.6882677 ]
289 Episode finished after 11 timesteps
0.7075148766161046
1.000326710485145
[ 0.08609027  0.24143663 -0.21716844 -0.6793262 ]
290 Episode finished after 13 timesteps
0.7073733842531508
1.0004684368723247
[-0.15091151 -1.0281699   0.21923918  1.7395314 ]
291 Episode finished after

0.6916002308128689
1.0004345179331722
[ 0.17759414  1.0095294  -0.24793513 -1.7688347 ]
355 Episode finished after 9 timesteps
0.6914273480443069
1.000338103984379
[ 0.18251798  1.5828285  -0.21174662 -2.502786  ]
356 Episode finished after 10 timesteps
0.6912199457666907
1.0002190581528174
[ 0.10386162  0.808085   -0.22297603 -1.4621652 ]
357 Episode finished after 12 timesteps
0.6910471580598836
1.000201842286818
[ 0.13713577  1.541101   -0.23923634 -2.5654998 ]
358 Episode finished after 10 timesteps
0.6908398698250066
1.0003093148819364
[ 0.07774804  0.9493685  -0.23606746 -1.8813893 ]
359 Episode finished after 13 timesteps
0.690632643768827
1.0002923082105222
[ 0.15240869  1.5332657  -0.24487981 -2.5238826 ]
360 Episode finished after 12 timesteps
0.690425479872694
1.0002700367602466
[ 0.14838907  1.5297722  -0.20987011 -2.5090961 ]
361 Episode finished after 12 timesteps
0.6902183781179618
1.0002909415872472
[ 0.15961443  1.184015   -0.23429869 -2.0287893 ]
362 Episode finished 

[-0.17966506 -1.5235081   0.24182835  2.5927005 ]
426 Episode finished after 12 timesteps
0.6740858294990577
1.0002546138634594
[ 0.09636427  0.75812536 -0.21738683 -1.6110675 ]
427 Episode finished after 16 timesteps
0.6738162423485479
1.000247431594956
[ 0.16861226  0.8169406  -0.2303418  -1.5183429 ]
428 Episode finished after 16 timesteps
0.6735467630140289
1.0003394955788585
[ 0.17341693  0.83086514 -0.23598099 -1.4721888 ]
429 Episode finished after 16 timesteps
0.6733447242414445
1.0002911062355535
[-0.09106243 -0.39275962  0.21743125  1.0008196 ]
430 Episode finished after 12 timesteps
0.6731090889356124
1.0002804483571839
[ 0.08906414  1.3600928  -0.24292967 -2.329659  ]
431 Episode finished after 15 timesteps
0.6726044337717693
1.0003098587949353
[-0.23377508 -1.7739246   0.22315672  2.5908732 ]
432 Episode finished after 29 timesteps
0.6724362994775964
1.0004675509925518
[-0.14293948 -1.2054511   0.21773478  2.0120082 ]
433 Episode finished after 10 timesteps
0.6721337636550

0.6579354590767492
1.0001989967507445
[ 0.18596937  0.93445176 -0.22968489 -1.6661742 ]
496 Episode finished after 13 timesteps
0.6577052162048057
1.000243312874003
[-0.19084695 -1.2249624   0.21979646  2.0374203 ]
497 Episode finished after 14 timesteps
0.6575079293022457
1.0002405006004362
[ 0.2266461   2.1742501  -0.25688744 -3.2454126 ]
498 Episode finished after 13 timesteps
0.6571792492973749
1.000240444229444
[-0.11935878 -1.5863774   0.25065312  2.726074  ]
499 Episode finished after 20 timesteps
0.6569492710591566
1.0002527765251357
[ 0.16160569  1.1999229  -0.22928424 -1.9305097 ]
500 Episode finished after 14 timesteps
0.6567850501643024
1.0002216190405306
[ 0.1522788   0.7511308  -0.22602393 -1.4486822 ]
501 Episode finished after 10 timesteps
0.6566208703205666
1.0002344069483418
[ 0.12160987  1.5413985  -0.24637547 -2.603643  ]
502 Episode finished after 10 timesteps
0.6564239086811117
1.0002835794351994
[ 0.1698052   1.367798   -0.21377164 -2.1739092 ]
503 Episode finish

0.6415943248689169
1.0002798439612282
[-0.06521757 -0.5600216   0.2215667   1.2967552 ]
569 Episode finished after 13 timesteps
0.6414339423267559
1.0002966559453246
[ 0.17785971  1.5378721  -0.2185346  -2.450456  ]
570 Episode finished after 10 timesteps
0.6412415361962273
1.0003375076802596
[ 0.15208218  1.2247939  -0.23377506 -2.0572026 ]
571 Episode finished after 12 timesteps
0.641017135320934
1.0001740313807834
[-0.14434113 -1.5408399   0.2172499   2.4497802 ]
572 Episode finished after 14 timesteps
0.640824854216878
1.0003679222771262
[-0.15432996 -0.8402435   0.22713533  1.3900049 ]
573 Episode finished after 12 timesteps
0.6406005991584035
1.0003416144778992
[ 0.12937127  0.5696012  -0.216376   -1.1914922 ]
574 Episode finished after 13 timesteps
0.6404404650228283
1.0003002575944668
[ 0.10670549  1.5437372  -0.2375239  -2.5911896 ]
575 Episode finished after 10 timesteps
0.6402163444803929
1.0002151316931793
[ 0.09313589  1.5674468  -0.23774779 -2.6392748 ]
576 Episode finish

0.6255964908517342
1.000296233817661
[-0.13809954 -0.84572035  0.23486154  1.6705674 ]
641 Episode finished after 18 timesteps
0.625408835362783
1.0002455802949208
[-0.19624    -1.1333203   0.24156952  1.9974741 ]
642 Episode finished after 12 timesteps
0.6252524987883815
1.0001727121034492
[ 0.08851585  1.4222836  -0.2114321  -2.2557993 ]
643 Episode finished after 9 timesteps
0.6250024415521644
1.0003366980701685
[ 0.1944763   1.5269084  -0.21052755 -2.3466759 ]
644 Episode finished after 16 timesteps
0.6247524843213397
1.000225164731546
[ 0.16296285  1.7639047  -0.23782077 -2.6821475 ]
645 Episode finished after 17 timesteps
0.624502627055912
1.0002171442640246
[-0.20681894 -1.18448     0.22159459  1.9027152 ]
646 Episode finished after 16 timesteps
0.6243152996850826
1.0003106760792435
[ 0.18959554  1.7184222  -0.23312032 -2.7895572 ]
647 Episode finished after 11 timesteps
0.62412802850544
1.000242563493719
[-0.18335158 -0.79142493  0.23234843  1.4038314 ]
648 Episode finished aft

0.6069854527384887
1.0151743546749155
[-0.23270462 -1.9768641   0.23164295  2.9548264 ]
719 Episode finished after 16 timesteps
0.6066820282888791
1.0103294834649812
[-0.10839575 -0.62615794  0.21459655  1.2576002 ]
720 Episode finished after 19 timesteps
0.6065303729480993
1.01232669605977
[-0.13591401 -1.5990725   0.22111121  2.465109  ]
721 Episode finished after 10 timesteps
0.6061968646283956
1.0118355951271951
[ 0.2902982   1.3972164  -0.23999427 -1.8244877 ]
722 Episode finished after 23 timesteps
0.6060453305664025
1.0154204064747319
[ 0.1084372   1.360766   -0.23355533 -2.2186537 ]
723 Episode finished after 9 timesteps
0.6058635396924175
1.0153597749939018
[ 0.17650752  1.156637   -0.2523157  -1.9609877 ]
724 Episode finished after 12 timesteps
0.6056515192587103
1.0116409735221947
[ 0.09803698  0.6073932  -0.23297848 -1.2484951 ]
725 Episode finished after 15 timesteps
0.6055001215194267
1.012046307946245
[-0.16436143 -1.2183177   0.22036578  2.024233  ]
726 Episode finished

0.5912294411817395
1.0141656292941084
[-0.18041033 -1.6084943   0.25212988  2.5499594 ]
788 Episode finished after 12 timesteps
0.591052094519011
1.0132443773644892
[ 0.10767749  0.82725936 -0.22540152 -1.4017651 ]
789 Episode finished after 12 timesteps
0.590756634956247
1.013645378484701
[ 0.19816826  0.6108152  -0.23225833 -1.1056557 ]
790 Episode finished after 19 timesteps
0.590579430117657
1.0126300918248792
[ 0.08352008  0.6020747  -0.21185888 -1.2153585 ]
791 Episode finished after 13 timesteps
0.5903727583199524
1.0118041768526802
[ 0.20397705  1.1983628  -0.23931503 -1.9747646 ]
792 Episode finished after 14 timesteps
0.5902251798889535
1.0201307856477797
[ 0.13338663  1.4116422  -0.23169048 -2.224538  ]
793 Episode finished after 9 timesteps
0.5900776383488731
1.012525812163949
[ 0.1685747   0.57762104 -0.21021481 -1.026114  ]
794 Episode finished after 11 timesteps
0.5898416485948379
1.0080010407338185
[ 0.21937983  1.4031136  -0.25254905 -2.199362  ]
795 Episode finished a

0.575997612023176
1.0053839222993701
[ 0.1211549   0.9629712  -0.22361329 -1.7550064 ]
855 Episode finished after 11 timesteps
0.5758248343380397
1.0136291119735688
[ 0.12453377  0.55335855 -0.23045528 -1.2086747 ]
856 Episode finished after 11 timesteps
0.5756521084797299
1.0081054148348896
[-0.15294866 -1.1390485   0.21208037  1.8870587 ]
857 Episode finished after 12 timesteps
0.575536986692528
1.0033663368667476
[-0.06505641 -1.3573558   0.22772     2.2806997 ]
858 Episode finished after 9 timesteps
0.5753643471777184
1.0127670917194336
[ 0.15449749  0.9630465  -0.23099793 -1.7756169 ]
859 Episode finished after 11 timesteps
0.5752205204743135
1.0066577750258148
[-0.1443697  -1.3958145   0.23137446  2.2259285 ]
860 Episode finished after 11 timesteps
0.5749617230039076
1.0114686990273185
[-0.1758649  -1.3464926   0.21229537  2.1307127 ]
861 Episode finished after 17 timesteps
0.5747317785580023
1.0120146992926797
[-0.07195754 -0.8406981   0.232057    1.6195685 ]
862 Episode finishe

0.561326577019229
1.0083454999451835
[-0.17243323 -1.5861828   0.25879502  2.534479  ]
925 Episode finished after 10 timesteps
0.5610179245726965
1.0116440104320645
[ 0.24942814  1.9263926  -0.25439933 -2.841133  ]
926 Episode finished after 22 timesteps
0.5608496402320943
1.0109109142371877
[ 0.1359767   1.1799144  -0.21351293 -1.9347277 ]
927 Episode finished after 12 timesteps
0.560681406370484
1.0145313870161772
[ 0.16896178  1.1697634  -0.2166094  -1.8374456 ]
928 Episode finished after 12 timesteps
0.5604291501930573
1.0080863337772077
[ 0.13723356  1.2142332  -0.23034297 -2.0123334 ]
929 Episode finished after 18 timesteps
0.5602050177590979
1.0108748968690633
[-0.2156524 -1.1856544  0.2412666  2.0184457]
930 Episode finished after 16 timesteps
0.5600369772600579
1.0143555094487966
[ 0.10937921  1.3675065  -0.23364261 -2.2719624 ]
931 Episode finished after 11 timesteps
0.5598689871668664
1.0070542956025086
[ 0.19534677  1.5986669  -0.24235103 -2.448192  ]
932 Episode finished a

0.5471386423710253
1.00814419803926
[ 0.17522036  0.9846508  -0.22316019 -1.4707094 ]
996 Episode finished after 27 timesteps
0.5469471725685808
1.0118477989274721
[-0.18389572 -1.6010488   0.22686665  2.5868764 ]
997 Episode finished after 14 timesteps
0.54667376050565
1.0107120619569387
[ 0.22162679  1.7775067  -0.21986614 -2.549105  ]
998 Episode finished after 19 timesteps
0.5464004851179957
1.0103021238930523
[ 0.13298659  1.3487417  -0.24510942 -2.2558713 ]
999 Episode finished after 21 timesteps
0.5462092736318396
1.0127955122928445
[ 0.18422505  1.3430042  -0.22712491 -2.2195158 ]
1000 Episode finished after 13 timesteps
0.5457724700374877
1.0086259600976784
[ 0.17456342  0.37210312 -0.22160822 -0.7763756 ]
1001 Episode finished after 32 timesteps
0.5456087587615798
1.0100225566632368
[ 0.15511958  1.6142726  -0.26155055 -2.515697  ]
1002 Episode finished after 12 timesteps
0.5454178243380862
1.0138882658045207
[ 0.13313323  1.7154162  -0.25713322 -2.8600051 ]
1003 Episode fini

0.5330960316189006
1.0120661887340248
[ 0.158918    1.3723091  -0.23009492 -2.2391343 ]
1071 Episode finished after 11 timesteps
0.5328828305192439
1.015045860200189
[-0.2010459  -1.7262266   0.23335908  2.640688  ]
1072 Episode finished after 17 timesteps
0.5326963495025796
1.0128916102306296
[ 0.15549088  1.0015233  -0.24149117 -1.7339236 ]
1073 Episode finished after 13 timesteps
0.5325365605725103
1.007081505546177
[-0.20316698 -1.1551875   0.2459002   1.9489034 ]
1074 Episode finished after 12 timesteps
0.5324034397451155
1.0080854365602137
[-0.08898082 -0.99369025  0.21028191  1.6781015 ]
1075 Episode finished after 11 timesteps
0.531818103321919
1.0072742542360238
[ 0.45257497  0.6913881  -0.21357492 -0.06896418]
1076 Episode finished after 44 timesteps
0.5316054133041349
1.0090925491104523
[-0.23766986 -1.56359     0.2486941   2.5286257 ]
1077 Episode finished after 16 timesteps
0.5314725252402797
1.0134262989740819
[-0.12121387 -1.7167386   0.22614919  2.8030095 ]
1078 Episode

0.5201155318638637
1.0130994899819294
[-0.15426408 -0.7512968   0.2295212   1.4530815 ]
1143 Episode finished after 16 timesteps
0.5199595167073368
1.0116620080855985
[ 0.06443042  0.99550736 -0.21520613 -1.7648364 ]
1144 Episode finished after 13 timesteps
0.519777558172089
1.0068112758274834
[ 0.1379318   1.9044907  -0.22626579 -3.0124652 ]
1145 Episode finished after 14 timesteps
0.5196476267763352
1.0063081542029977
[ 0.18205622  1.2158165  -0.21932037 -1.921272  ]
1146 Episode finished after 10 timesteps
0.5194398040973213
1.0074676546500996
[ 0.20684238  1.3871586  -0.2239289  -2.2344646 ]
1147 Episode finished after 15 timesteps
0.5192580274342046
1.0077953656705527
[ 0.20736896  1.9682276  -0.24144484 -3.0304813 ]
1148 Episode finished after 14 timesteps
0.518972506906386
1.0083218446551738
[ 0.12893848  0.23053145 -0.21069938 -0.79691094]
1149 Episode finished after 23 timesteps
0.5188427767533234
1.0119096266312733
[ 0.11302856  1.1405368  -0.22361647 -2.012772  ]
1150 Episod

0.5067664839361788
1.0094488300930928
[ 0.2136284   1.5656     -0.22824606 -2.4782474 ]
1221 Episode finished after 18 timesteps
0.5065384846220705
1.008117430170791
[ 0.1950383   1.3646965  -0.24034265 -2.2742162 ]
1222 Episode finished after 19 timesteps
0.5063865420706108
1.0064400081226432
[-0.09489878 -0.44073218  0.21244188  0.888936  ]
1223 Episode finished after 12 timesteps
0.5061840228972961
1.010350601814155
[ 0.16526353  1.3575647  -0.26089063 -2.3723054 ]
1224 Episode finished after 15 timesteps
0.506082793685224
1.008522343588993
[ 0.15800561  0.5525568  -0.22822146 -1.137747  ]
1225 Episode finished after 9 timesteps
0.505930987823958
1.0091307958122342
[-0.15607506 -1.7715772   0.22602285  2.7644808 ]
1226 Episode finished after 11 timesteps
0.5058045177246443
1.0089341797348526
[ 0.15523857  0.79518276 -0.23704517 -1.4209076 ]
1227 Episode finished after 10 timesteps
0.5055516723612038
1.007558407678612
[-0.11954097 -0.00993524  0.21634802  0.3460945 ]
1228 Episode fin

0.49366130197867375
1.0084267101677444
[ 0.132398    0.95682085 -0.2381912  -1.9223695 ]
1298 Episode finished after 25 timesteps
0.49348854643803985
1.0085462871550892
[ 0.16971743  1.0110794  -0.2136864  -1.7224307 ]
1299 Episode finished after 13 timesteps
0.4933405183786952
1.0082620383155616
[-0.16179942 -1.1782469   0.23900107  1.9621736 ]
1300 Episode finished after 12 timesteps
0.4932171955819968
1.0078112739397005
[-0.08667056 -1.1691445   0.2405141   2.0223353 ]
1301 Episode finished after 10 timesteps
0.49311855954089173
1.0048945267335512
[ 0.10677676  0.9712136  -0.23825108 -1.7652435 ]
1302 Episode finished after 9 timesteps
0.4929213466319229
1.0083740547997877
[-0.19453397 -1.7397048   0.23807414  2.7479885 ]
1303 Episode finished after 15 timesteps
0.49277348871125154
1.0046727263146418
[ 0.2149235   1.2245985  -0.22797056 -1.9939023 ]
1304 Episode finished after 12 timesteps
0.49257641380646205
1.0061664557142649
[ 0.17061713  2.1068366  -0.2601845  -3.2488186 ]
1305 

[-0.1662394  -0.9625655   0.21455069  1.580844  ]
1371 Episode finished after 13 timesteps
0.48099121624494967
1.0084540914871136
[-0.04561525 -0.93914306  0.2209889   1.7485102 ]
1372 Episode finished after 23 timesteps
0.4808709804650676
1.0115154192575977
[-0.08900192 -0.81104034  0.23419847  1.4916863 ]
1373 Episode finished after 10 timesteps
0.4805585080804176
1.0182614767497096
[-0.12610991 -0.2493396   0.22704282  0.90777224]
1374 Episode finished after 25 timesteps
0.48029426696785776
1.0174260503951122
[-0.21595618 -0.9905311   0.24251641  1.6455908 ]
1375 Episode finished after 23 timesteps
0.4801742054078721
1.008766801872601
[-0.17032276 -1.1993867   0.22612026  1.8837038 ]
1376 Episode finished after 10 timesteps
0.4799821693345423
1.0132693218067288
[-0.15925634 -0.8260713   0.23478116  1.559168  ]
1377 Episode finished after 16 timesteps
0.479622308675566
1.0126764820888638
[-0.352959   -2.7249007   0.26457983  3.4534779 ]
1378 Episode finished after 30 timesteps
0.4794

0.46572633711765793
1.0075468726766605
[-0.16769135 -0.6190257   0.21300082  1.0098236 ]
1443 Episode finished after 13 timesteps
0.46560991717595485
1.0196352051571012
[-0.14866783 -0.63756394  0.21239139  1.1806002 ]
1444 Episode finished after 9 timesteps
0.4654237057985196
1.015833806184431
[-0.1743585  -0.36053327  0.22889666  0.86876285]
1445 Episode finished after 16 timesteps
0.4650282538530968
1.0122436814320583
[-0.04060553 -1.2246809   0.20988     2.2282891 ]
1446 Episode finished after 34 timesteps
0.4649120084147586
1.0142553163692356
[-0.16886492 -1.3998568   0.23047835  2.2623925 ]
1447 Episode finished after 11 timesteps
0.46474931361766003
1.0135598975735216
[-0.06054557 -0.03634546  0.21374524  0.49056363]
1448 Episode finished after 14 timesteps
0.46463313790740757
1.0187299499909084
[-0.20037432 -1.1415806   0.22701964  1.8749057 ]
1449 Episode finished after 10 timesteps
0.4644008736027131
1.0249294732256156
[ 0.09059683 -0.3106229  -0.21533677 -0.21570008]
1450 Ep

0.4480017919004626
1.0133260545759077
[-0.14656942 -0.06548967  0.22145797  0.45767677]
1510 Episode finished after 18 timesteps
0.447621142659883
1.0077775088279988
[ 0.3322633   0.41839415 -0.21241443 -0.4342664 ]
1511 Episode finished after 34 timesteps
0.44717373407349337
1.011586591338691
[ 0.3970078   1.5502795  -0.22329912 -1.3839451 ]
1512 Episode finished after 40 timesteps
0.4469501975067947
1.0142266196716163
[-0.13422309 -0.60408795  0.23356588  1.2132136 ]
1513 Episode finished after 19 timesteps
0.4461240833795702
1.0120964796074692
[-0.06106219 -1.0035526   0.2098015   1.1954423 ]
1514 Episode finished after 75 timesteps
0.44489889692387835
1.0097421853815916
[ 0.59762657 -0.77350295  0.23368494  1.5768138 ]
1515 Episode finished after 110 timesteps
0.44465426369499345
1.0136009767185896
[-0.15484382  0.17702782  0.21084426  0.23525214]
1516 Episode finished after 21 timesteps
0.4445208840893083
1.0152861257859815
[ 0.17359385  0.23220073 -0.2240816  -0.66629875]
1517 Ep

0.42751785865925346
1.0222829764398436
[-0.20429567 -0.41363233  0.21761467  0.83610415]
1582 Episode finished after 16 timesteps
0.4274109898820007
1.0124731114030712
[-0.10148468 -0.82724684  0.21364586  1.4166381 ]
1583 Episode finished after 10 timesteps
0.42685570272771484
1.0137808281270897
[ 0.3809474  -0.41626638  0.21524869  1.7075964 ]
1584 Episode finished after 52 timesteps
0.42666365607401896
1.0140560037689283
[ 0.21350776  0.21719205 -0.21854113 -0.4899516 ]
1585 Episode finished after 17 timesteps
0.4259389259354501
1.0101807968110652
[ 0.38048786  1.552432   -0.24379826 -1.9524033 ]
1586 Episode finished after 68 timesteps
0.4257685801778194
1.0120163935547073
[-0.15982987 -0.40761882  0.22630282  0.83799744]
1587 Episode finished after 16 timesteps
0.4253855512687209
1.0120091797251787
[-0.20017897 -1.1989244   0.23438217  1.6335428 ]
1588 Episode finished after 36 timesteps
0.4250453704135993
1.0101197073236108
[ 0.19023578  0.01636011 -0.21106878  0.02386532]
1589 E

0.40652474618297135
1.0059382743811944
[ 0.25228646  1.3060081  -0.22899067 -1.298595  ]
1652 Episode finished after 43 timesteps
0.4062605843557464
1.0073745566094294
[-0.22210495 -0.01990903  0.21929225  0.31941798]
1653 Episode finished after 26 timesteps
0.4056922032875889
1.0105480658821762
[-0.11504842 -0.9425397   0.22869143  1.416208  ]
1654 Episode finished after 55 timesteps
0.4046387473086566
1.012338386490368
[ 1.4446281  -1.0705864   0.21045183  2.9595919 ]
1655 Episode finished after 105 timesteps
0.4044971449888626
1.0156697113998234
[-0.10229237 -0.24951237  0.21354102  0.6929462 ]
1656 Episode finished after 13 timesteps
0.4039312310700905
1.0080803698098117
[-0.00473437 -0.7428452   0.21769267  1.1741097 ]
1657 Episode finished after 56 timesteps
0.4037898763438385
1.0108944562130742
[-0.11609152 -0.16159217  0.22098969  0.72075963]
1658 Episode finished after 15 timesteps
0.403628388655766
1.013001341605559
[-0.14913657  0.15837562  0.21108009  0.23185234]
1659 Episo

0.3802554004092293
1.0064402865342952
[ 5.1789108e-04 -5.6014013e-01 -2.1197638e-01 -2.1880968e-01]
1719 Episode finished after 49 timesteps
0.38012233098083104
1.0066147568420722
[-0.13524535 -0.7525674   0.22303301  1.3912804 ]
1720 Episode finished after 14 timesteps
0.3798183471261416
1.00914019139794
[ 0.19765618  0.5670106  -0.2238503  -0.92493784]
1721 Episode finished after 31 timesteps
0.37930592550929154
1.0110563109327038
[-0.26034704 -0.18289346  0.2096302   0.10032154]
1722 Episode finished after 55 timesteps
0.3791921479546628
1.0068983519873158
[-0.23441698 -1.1671116   0.24720363  1.8714491 ]
1723 Episode finished after 12 timesteps
0.37871844205484273
1.0107844407023976
[-0.09156582 -0.7924481   0.22183546  1.0765393 ]
1724 Episode finished after 50 timesteps
0.37832098645491957
1.0118204405414872
[ 0.30977762  1.3383138  -0.20966274 -1.4287555 ]
1725 Episode finished after 41 timesteps
0.37820750434507433
1.0155389700667001
[-0.13812676 -0.23030534  0.21226816  0.6617

0.35014279980929747
1.0137090673834137
[-0.20718561 -0.02717934  0.21160959 -0.034019  ]
1787 Episode finished after 72 timesteps
0.3497753336362694
1.0115753512307093
[ 0.28753826  0.71964437 -0.22645561 -0.75557333]
1788 Episode finished after 42 timesteps
0.3490764645991247
1.01332631980913
[ 0.3444641  -0.20237443  0.20974067  0.59591633]
1789 Episode finished after 81 timesteps
0.34869268201254283
1.0134836608045843
[-0.09414668 -0.4041076   0.22358783  0.87142354]
1790 Episode finished after 44 timesteps
0.34813520588413743
1.0160720434727235
[ 0.362277    1.5046464  -0.21379997 -1.9383775 ]
1791 Episode finished after 64 timesteps
0.3475264868402548
1.0153106124797726
[ 0.16284594  0.6069771  -0.22701815 -0.7596762 ]
1792 Episode finished after 69 timesteps
0.34657207805459733
1.0123826863015617
[ 0.9462919  -0.81829715  0.23663588  2.6096222 ]
1793 Episode finished after 110 timesteps
0.3458277299388827
1.011476734764116
[-0.02355592 -0.17578992  0.21840447  0.31241494]
1794 Ep

0.3155725070474729
1.0157244237489067
[-0.01228105 -0.18955214  0.21429525  0.8626768 ]
1853 Episode finished after 33 timesteps
0.315430527817514
1.0099120915538686
[-0.21552655 -0.40753537  0.2100929   0.84641963]
1854 Episode finished after 18 timesteps
0.3149262299113646
1.0106677494026841
[-0.1582488  -0.95837706  0.22871375  1.5916746 ]
1855 Episode finished after 63 timesteps
0.31410846482459626
1.0107878085465434
[-0.44842115 -1.8732846   0.24866965  2.217659  ]
1856 Episode finished after 104 timesteps
0.314014244063431
1.0039934404829347
[-0.12329311 -1.1372848   0.21075977  1.9682539 ]
1857 Episode finished after 12 timesteps
0.31381019602634275
1.0182845750823617
[ 0.27239737  0.55835104 -0.21844839 -0.7056097 ]
1858 Episode finished after 27 timesteps
0.3130266308116189
1.0111809802284388
[ 0.02862754 -1.0320797   0.24979015  1.9222188 ]
1859 Episode finished after 99 timesteps
0.31258868921050437
1.0073711308193327
[ 0.32054     0.54961896 -0.21098992 -0.72659296]
1860 Ep

0.27492134106977234
1.016665531648791
[2.3056371  1.8433987  0.1849538  0.29144147]
1919 Episode finished after 200 timesteps
0.2737553756524236
1.0168902933826263
[ 2.3873298   2.199157    0.210337   -0.02294201]
1920 Episode finished after 170 timesteps
0.2736048478315333
1.0147188035992993
[-0.12079573 -0.02148078  0.2187696   0.33567685]
1921 Episode finished after 22 timesteps
0.2722402039288287
1.0191822466990401
[ 1.6637514   1.4953111   0.09281488 -0.09150717]
1922 Episode finished after 200 timesteps
0.2717098395452849
1.0156041458611944
[ 0.6236096   1.1108392  -0.23235647 -1.2333827 ]
1923 Episode finished after 78 timesteps
0.2703546472715404
1.0155089128067503
[ 1.2209812   1.1299856   0.10293761 -0.07075524]
1924 Episode finished after 200 timesteps
0.2694908735807597
1.015628220151282
[-0.35378626 -0.5142185  -0.21429348 -0.07299625]
1925 Episode finished after 127 timesteps
0.26932922351519517
1.0127715648394888
[-0.11396186 -0.75277996  0.21639699  1.3551153 ]
1926 Epi

0.21519162286524096
1.0143764001298603
[ 0.68294364  0.7167917   0.06735595 -0.05056306]
1984 Episode finished after 200 timesteps
0.214482643244936
1.0144074357253365
[-0.8847043 -1.0580411 -0.2152007 -0.1382437]
1985 Episode finished after 132 timesteps
0.21341287992144245
1.0116880769781702
[1.124996   0.73840225 0.09929602 0.38266277]
1986 Episode finished after 200 timesteps
0.21281614475826413
1.0135139585950779
[ 0.11197449  0.2473048  -0.21743771 -0.6756128 ]
1987 Episode finished after 113 timesteps
0.2117546933379286
1.0150306903372224
[1.7097489  1.4236038  0.13294871 0.10489188]
1988 Episode finished after 200 timesteps
0.21069853606066197
1.0118571372717928
[-0.4003997  -0.35155106 -0.05107639 -0.07810622]
1989 Episode finished after 200 timesteps
0.2096476465211572
1.0068658105783332
[-0.14554046  0.8236942  -0.01082892 -1.0455587 ]
1990 Episode finished after 200 timesteps
0.20860199844580732
1.0124038779387372
[0.49787763 0.4021129  0.03265765 0.15440536]
1991 Episode f

0.1585343455989591
1.0155863922356099
[-0.32202348 -0.7651405  -0.04334509  0.48337445]
2048 Episode finished after 200 timesteps
0.15774363253299725
1.0192727538319446
[ 0.5669215   0.69555795  0.01668979 -0.14323397]
2049 Episode finished after 200 timesteps
0.15695686326325398
1.018034340097129
[1.1980445  0.67819893 0.05605335 0.41665563]
2050 Episode finished after 200 timesteps
0.15638500069974057
1.0159598800053897
[ 0.27522948  0.6369926  -0.21362492 -0.9636813 ]
2051 Episode finished after 147 timesteps
0.15560500780352274
1.0184574297988487
[-0.4916299  -1.0923417  -0.12080549  0.5695694 ]
2052 Episode finished after 200 timesteps
0.15482890523512044
1.01560457295682
[1.0659297  0.7221843  0.06726732 0.19775614]
2053 Episode finished after 200 timesteps
0.15415684548544992
1.0166854660844344
[-1.8365216  -1.2013553  -0.21624549 -1.255346  ]
2054 Episode finished after 173 timesteps
0.15338796583686473
1.0168451893420647
[-0.01610892  0.02114248  0.01218053 -0.06029293]
2055 E

0.11896913426935067
1.0284865976579918
[1.1811484  1.6099118  0.21103618 0.09368091]
2112 Episode finished after 131 timesteps
0.11842904085030213
1.025047230215239
[-2.1072643  -2.1514816  -0.21314138  0.02136151]
2113 Episode finished after 182 timesteps
0.11783835881458389
1.0220972779677857
[-2.007217   -2.2233531  -0.21221955 -0.06658433]
2114 Episode finished after 200 timesteps
0.11732686247734471
1.0168862677592083
[-2.3188844  -1.9204749  -0.21160921 -0.8121161 ]
2115 Episode finished after 175 timesteps
0.1169286185870063
1.019882749723857
[1.5947568  1.767697   0.21146438 0.08755914]
2116 Episode finished after 136 timesteps
0.11644435824849496
1.0247070369745106
[1.3599952  1.2690561  0.20964232 0.47197402]
2117 Episode finished after 165 timesteps
0.11586357510540524
1.0203027877644824
[-1.1146871  -1.1055539  -0.12697925 -0.2534395 ]
2118 Episode finished after 200 timesteps
0.11537218756459953
1.0152740473273512
[ 1.4101609   2.0240812   0.20955142 -0.03464227]
2119 Epis

In [5]:
action=0
agent.epsilon = 0
scores = []
for i_episode in range(5):
    state = env.reset()
    score = 0
    
    #env is limited to 200 timesteps by default so range(>200 is fine)
    for t in range(1000):
        env.render()
        action = agent.getAction(state)
        n_state, reward, done, info = env.step(action)
        sleep(0.016) #Limit to 60 FPS
        state = n_state
        score += reward
        if done:
            scores.append(score)
            break
print(f' Mean score = {np.mean(score)}')
env.close()

 Mean score = 134.0


In [6]:
##USE THIS CELL TO SAVE TRAINED AGENT

# import pickle
# from datetime import datetime

# with open(f'RL-cart1-{datetime.now()}.pkl', 'wb') as outp:
#     pickle.dump(agent, outp, pickle.HIGHEST_PROTOCOL)