In [1]:
from DQNAgent import Experience, ExperienceReplay, Net, DQNAgent
import numpy as np
from time import sleep

In [2]:
from datetime import datetime
import os
dt = datetime.now()
directory = f"CartPole_results/result-{dt.strftime('%m-%d-%Y_%H-%M-%S')}"
os.mkdir(directory)

In [3]:
import gym
train_dir = directory+'/'+'training'
os.mkdir(directory+'/'+'training')
env = gym.make('CartPole-v0')
env = gym.wrappers.Monitor(env, train_dir, video_callable=lambda episode_id: episode_id % 200 == 0,force=True)
print(env.action_space)

Discrete(2)


C:\Users\mrida\anaconda3\lib\site-packages\gym\wrappers\monitor.py:31: UserWarning: The Monitor wrapper is being deprecated in favor of gym.wrappers.RecordVideo and gym.wrappers.RecordEpisodeStatistics (see https://github.com/openai/gym/issues/2297)
  warnings.warn(


In [4]:
#Change hyperparameters here
agent = DQNAgent(layerSizes=[4, 64, 2],
                epsilon=1, eps_decay=0.9997,min_eps=0.001, batch_size=32, discount_fact=0.99, 
                 lr=0.15, num_actions=2, target_update_freq=10000, mem_size = 65000,
                    update_freq = 2)

In [5]:
i_episode = 0
last_n_scores = [0]
n = 10
progress = []
running = []
done = False

while np.mean(last_n_scores) < 195:
    
    i_episode += 1
    state = env.reset()
    score = 0
    agent.loss_val = 0
    running = []
    
    for t in range(1000):
        action = agent.getAction(state)
        n_state, reward, done, info = env.step(action)
        score += reward
        agent.step(state, action, reward, n_state, int(done))
        running.append(action)
        state = n_state
        
        if done:
            print(agent.epsilon)
            print(agent.loss_val/t+1)
            print(n_state)
            print(f"{i_episode} Episode finished after {t+1} timesteps")
            if len(last_n_scores) == n:
                last_n_scores.pop(0)
            last_n_scores.append(score)
            if i_episode % 250 == 0:
                progress.append(running)
            break
progress.append(running)
env.close()

0.9976025184885671
1.036906758051676
[ 0.42824188  0.61528426 -0.21332388 -0.44322297]
1 Episode finished after 49 timesteps
0.9955094377260496
1.0027082105203031
[ 0.11076825  0.4061242  -0.21448398 -1.0284154 ]
2 Episode finished after 14 timesteps
0.990741728889455
1.0012007118090085
[-0.2234841  -1.1569227   0.22208406  1.6022671 ]
3 Episode finished after 32 timesteps
0.9848141897434964
1.0023094259787542
[ 0.19407713  1.5250804  -0.25345278 -2.1434176 ]
4 Episode finished after 40 timesteps
0.9833378545257923
1.0009365414007334
[-0.1264863  -0.96603185  0.23967905  1.764642  ]
5 Episode finished after 9 timesteps
0.9809803202000744
1.0008220922609325
[ 0.0799071   0.98616093 -0.24844883 -1.865806  ]
6 Episode finished after 17 timesteps
0.9792158794175366
1.0013838381379505
[ 0.16825913  0.8222725  -0.21254219 -1.4203656 ]
7 Episode finished after 12 timesteps
0.9777479366283534
1.000856075312994
[-0.1788426  -1.1980685   0.24555157  1.9997294 ]
8 Episode finished after 10 timest

0.8061928343937392
1.001250121043995
[-0.17525999 -0.45537838  0.21014106  0.9907259 ]
70 Episode finished after 16 timesteps
0.8040187239780371
1.0004971177558117
[-0.16339852 -0.58411217  0.22165142  1.1631397 ]
71 Episode finished after 19 timesteps
0.802331803493502
1.0008157472475432
[-0.17489393 -1.182601    0.21527158  1.9093181 ]
72 Episode finished after 14 timesteps
0.8011290276702879
1.0014747366076335
[ 0.10727011  1.6139092  -0.24848868 -2.5824587 ]
73 Episode finished after 10 timesteps
0.7958581982966219
1.0009517719816012
[-0.30395022 -1.7209789   0.22028488  2.245716  ]
74 Episode finished after 43 timesteps
0.7934738443502082
1.0011235896105064
[-0.13440445 -0.6125945   0.21589965  1.2771003 ]
75 Episode finished after 21 timesteps
0.7913340340269295
1.0012912565760095
[-0.11147541 -0.4135683   0.2222828   0.9393528 ]
76 Episode finished after 18 timesteps
0.7894368253109825
1.0005638912428236
[ 0.10454336  0.64651304 -0.21271299 -1.2840098 ]
77 Episode finished after

0.6540550951413465
1.000681435454171
[-0.02868801 -0.4523162   0.23149742  1.5461726 ]
147 Episode finished after 26 timesteps
0.6528786785913603
1.0007797456152427
[-0.1059747  -0.16368705  0.20962824  0.5496108 ]
148 Episode finished after 13 timesteps
0.6509226846000178
1.0010546805922211
[-0.16246746 -0.827413    0.21962063  1.5163299 ]
149 Episode finished after 20 timesteps
0.6489725506752079
1.0011299604145614
[-0.03418203 -0.3761804   0.21594457  1.2673553 ]
150 Episode finished after 20 timesteps
0.6478052758465697
1.0007427984250667
[-0.11371205 -0.36377528  0.21297362  1.0191498 ]
151 Episode finished after 12 timesteps
0.6460582990223163
1.001240941000801
[-0.12322658 -1.1801405   0.22659163  1.9560357 ]
152 Episode finished after 18 timesteps
0.6448962659139869
1.0015654575757005
[-0.2002413  -1.1530818   0.22960396  1.9328972 ]
153 Episode finished after 12 timesteps
0.6433501390396659
1.000955759116914
[-0.17535108 -0.824813    0.23846076  1.5032606 ]
154 Episode finishe

0.5620938684725512
1.0010360551273658
[-0.15028864 -0.75490594  0.23155057  1.4375561 ]
212 Episode finished after 10 timesteps
0.5595697509523695
1.001135762234957
[-0.21079347 -1.5646952   0.23382634  2.532527  ]
213 Episode finished after 30 timesteps
0.557725938153106
1.0009904187696521
[-0.15314023 -1.0058734   0.21557374  1.6507424 ]
214 Episode finished after 21 timesteps
0.5565557672581146
1.0013235827052716
[-0.138315   -0.41717136  0.21697493  0.9767681 ]
215 Episode finished after 14 timesteps
0.5552214350960321
1.0009820325321925
[-0.13526718 -0.57842875  0.21124643  1.2492446 ]
216 Episode finished after 17 timesteps
0.5542227857620446
1.0011999341077171
[-0.19925286 -1.5617975   0.24314658  2.563259  ]
217 Episode finished after 12 timesteps
0.5533919502342911
1.0011856122453335
[-0.16841862 -1.2187701   0.22441578  2.0311246 ]
218 Episode finished after 10 timesteps
0.5523965915042379
1.001050435535779
[-0.17919321 -1.1705991   0.21773364  1.8456596 ]
219 Episode finishe

0.4814708247839062
1.001763067306456
[-0.20096932 -1.744915    0.24291362  2.6475682 ]
281 Episode finished after 17 timesteps
0.4803165073831924
1.001690664095804
[-0.14071281 -1.2030066   0.23607607  2.083307  ]
282 Episode finished after 16 timesteps
0.47959646477730833
1.001267266907962
[-0.12591888 -1.0034549   0.23648015  1.7966987 ]
283 Episode finished after 11 timesteps
0.47859021818551184
1.0014288296134999
[-0.17195843 -0.8116523   0.21336918  1.5013535 ]
284 Episode finished after 14 timesteps
0.47744280698585945
1.0014237963439276
[-0.15021448 -1.1699136   0.21871994  1.9471143 ]
285 Episode finished after 16 timesteps
0.47629814668334425
1.0016121904066364
[-0.08180247 -0.22076465  0.21979633  0.8355135 ]
286 Episode finished after 15 timesteps
0.4751562306827412
1.0008654124006473
[-0.15167138 -1.583046    0.2437158   2.529113  ]
287 Episode finished after 16 timesteps
0.4738748472889159
1.0007421651937287
[-0.12074717 -1.1363953   0.2168022   1.9572955 ]
288 Episode fin

0.4062708932898965
1.001432925526222
[-0.08493016 -0.7998044   0.21126649  1.5713505 ]
359 Episode finished after 12 timesteps
0.4052968663346007
1.0012112164637075
[-0.13919792 -0.42717397  0.23055965  0.87597257]
360 Episode finished after 16 timesteps
0.404082615875433
1.0012535257523671
[-0.12244479 -1.0141442   0.23551391  1.7758813 ]
361 Episode finished after 19 timesteps
0.4033558124602332
1.0014364405942615
[-0.13943534 -1.373974    0.22587745  2.1789556 ]
362 Episode finished after 13 timesteps
0.4025095272154955
1.0010787346206296
[-0.13498539 -0.5755388   0.2380904   1.3004842 ]
363 Episode finished after 13 timesteps
0.40202673309451387
1.0010488978005014
[-0.13511193 -0.93603516  0.23556334  1.6776284 ]
364 Episode finished after 9 timesteps
0.4008222798016165
1.0014622813679226
[-0.15492938 -0.95975     0.24654716  1.669545  ]
365 Episode finished after 19 timesteps
0.40022140701376024
1.0012928256829683
[-0.17942472 -0.7838253   0.2212907   1.3857557 ]
366 Episode finis

0.3536824114979332
1.0015857493854128
[-0.18509    -1.360348    0.22156997  2.188217  ]
431 Episode finished after 15 timesteps
0.35283446445544797
1.0011972834181506
[-0.11717051 -0.60376096  0.21801703  1.1889846 ]
432 Episode finished after 17 timesteps
0.35230553021453187
1.0013929070410086
[-0.11053308 -1.4110203   0.22043112  2.2057815 ]
433 Episode finished after 9 timesteps
0.35135544595420115
1.0012909010919329
[-0.12998037 -1.3317285   0.21929777  2.3435445 ]
434 Episode finished after 19 timesteps
0.35082872891031947
1.0012182982948918
[-0.11974508 -1.1944417   0.21725553  1.8999302 ]
435 Episode finished after 10 timesteps
0.35030280146810056
1.0014921879499323
[-0.16889179 -1.9942782   0.23433681  3.0658886 ]
436 Episode finished after 10 timesteps
0.3495678273263756
1.00181468989915
[-0.15698783 -1.5350114   0.21987958  2.5078776 ]
437 Episode finished after 14 timesteps
0.3487297449233689
1.0012882844544948
[-0.08119074 -0.37836277  0.22441092  1.0325872 ]
438 Episode fi

0.31189934046121315
1.0015696922147816
[-0.11098406 -0.8193668   0.21053194  1.4214963 ]
498 Episode finished after 12 timesteps
0.3114317720757276
1.001034871127922
[-0.1552388 -1.772444   0.2516766  2.7635887]
499 Episode finished after 11 timesteps
0.3107783536662031
1.001281544001988
[-0.10148879 -1.1427023   0.22346397  2.0200295 ]
500 Episode finished after 14 timesteps
0.31012630620099507
1.0010681559409325
[-0.08142226 -0.94914097  0.21245047  1.6789372 ]
501 Episode finished after 13 timesteps
0.3096613957716477
1.0010798066569906
[-0.18599202 -1.137408    0.24824882  1.9514679 ]
502 Episode finished after 10 timesteps
0.3091044231349635
1.0014948149910197
[-0.10594295 -0.8140456   0.21962042  1.4360884 ]
503 Episode finished after 12 timesteps
0.3087336647102093
1.001525996834971
[-0.08805671 -0.9868882   0.23262769  1.724593  ]
504 Episode finished after 9 timesteps
0.3081783607374996
1.0016930722843178
[-0.1233794  -1.1614213   0.21013339  1.9520794 ]
505 Episode finished a

0.27554802155268404
1.0010321111767553
[-0.19313736 -0.56127053  0.22496223  1.1361575 ]
567 Episode finished after 13 timesteps
0.27513494743918765
1.0013839703881078
[-0.0523888  -0.7586304   0.21677402  1.4833317 ]
568 Episode finished after 10 timesteps
0.27472249256520637
1.0012934856996354
[-0.19339952 -1.9142427   0.24777582  3.0622199 ]
569 Episode finished after 10 timesteps
0.2742283628056372
1.0017927005304954
[-0.09219729 -1.3566967   0.21962108  2.2465808 ]
570 Episode finished after 11 timesteps
0.2737351218128269
1.0015011841557377
[-0.21059607 -1.3262416   0.2548638   2.2049017 ]
571 Episode finished after 13 timesteps
0.2729150241881955
1.0013862756701808
[-0.26461244 -2.1722114   0.2619431   3.2385051 ]
572 Episode finished after 19 timesteps
0.27217903724887305
1.0015616790494986
[-0.16555274 -1.715671    0.24968109  2.6141326 ]
573 Episode finished after 19 timesteps
0.27168948227658185
1.0016849618055859
[-0.16501138 -1.4138844   0.23679705  2.3967478 ]
574 Episode

0.2430684537991116
1.0013205271796324
[-0.16658324 -1.7696694   0.25044316  2.7845767 ]
636 Episode finished after 11 timesteps
0.24270406981440273
1.0011755364015698
[-0.15379749 -2.0978222   0.26124     3.291231  ]
637 Episode finished after 11 timesteps
0.2421948497491979
1.0021539475419559
[-0.19716677 -0.5822182   0.20998704  1.1343013 ]
638 Episode finished after 13 timesteps
0.24190434668856267
1.001320096605923
[-0.13246721 -1.3476022   0.24300794  2.2865977 ]
639 Episode finished after 9 timesteps
0.24154170781713755
1.0015995704517182
[-0.09415356 -1.5213743   0.24983245  2.5680115 ]
640 Episode finished after 10 timesteps
0.24110725869396912
1.0020164670073428
[-0.07676363 -0.6180823   0.23850586  1.2351792 ]
641 Episode finished after 11 timesteps
0.24081806015541846
1.0007743846435915
[-0.12549427 -1.7352785   0.21598616  2.757554  ]
642 Episode finished after 9 timesteps
0.24045704973642837
1.0016472317802254
[-0.11509271 -1.7526909   0.23464149  2.822388  ]
643 Episode f

0.21416015281088277
1.025133736092936
[-0.10263927 -0.40740895  0.23219058  1.0077217 ]
707 Episode finished after 12 timesteps
0.21383910526798944
1.0228188131004572
[ 0.16081823  1.333799   -0.22091153 -2.304828  ]
708 Episode finished after 11 timesteps
0.2134544834458521
1.0130413415079766
[-0.24979332 -1.5986367   0.26153684  2.497315  ]
709 Episode finished after 12 timesteps
0.21307055342396278
1.0222981879487634
[-0.14256214 -1.535359    0.21426475  2.499176  ]
710 Episode finished after 12 timesteps
0.2126873139580146
1.0251892011612653
[-0.10205554 -1.4132476   0.2152424   2.173799  ]
711 Episode finished after 11 timesteps
0.2123684743482432
1.0208962979829974
[-0.16230865 -1.1856989   0.22615258  2.014414  ]
712 Episode finished after 10 timesteps
0.21205011271101687
1.023445651680231
[-0.14167853 -1.3222446   0.24487394  2.2098126 ]
713 Episode finished after 11 timesteps
0.21160520804870955
1.0206826409945886
[-0.11525781 -0.24978353  0.21245424  0.6232013 ]
714 Episode f

0.188124630025443
1.0197800524765626
[-0.11035336 -1.4069505   0.23267819  2.3462727 ]
772 Episode finished after 9 timesteps
0.1877862595580833
1.0185889427860577
[ 0.21463753  2.1751637  -0.26786903 -3.304701  ]
773 Episode finished after 13 timesteps
0.18750474912568516
1.0226484976010397
[-0.09832684 -1.3488225   0.2455549   2.2951715 ]
774 Episode finished after 9 timesteps
0.1872236607056522
1.011775622703135
[-0.11121465 -0.5913936   0.23206165  1.1715431 ]
775 Episode finished after 11 timesteps
0.1867747954406076
1.014230531702439
[-0.14715518 -0.35621232  0.2100213   0.95370656]
776 Episode finished after 16 timesteps
0.18621522688737457
1.0210061827674508
[-0.144816   -0.9853703   0.22777982  1.7758493 ]
777 Episode finished after 19 timesteps
0.18599186915122257
1.0128978670109063
[-0.15287672 -0.61238563  0.23304296  1.1876644 ]
778 Episode finished after 9 timesteps
0.18565733477536073
1.023056091571396
[-0.09093837 -1.5951017   0.21843572  2.5330956 ]
779 Episode finishe

0.1616254941226471
1.021620568405423
[-0.14704588 -0.17561187  0.21381095  0.59658444]
849 Episode finished after 19 timesteps
0.16138320130077555
1.020084071283539
[-0.21517313 -1.957948    0.23123933  3.0611396 ]
850 Episode finished after 10 timesteps
0.16114127170013864
1.016554675064981
[-0.12525642 -1.1357492   0.2291004   2.0058305 ]
851 Episode finished after 10 timesteps
0.1608997047762314
1.0119641272144184
[-0.1397527  -1.1321673   0.23956954  2.0442567 ]
852 Episode finished after 10 timesteps
0.16065849998536494
1.0152310214729772
[-0.20778519 -1.2038808   0.2522116   1.9403107 ]
853 Episode finished after 10 timesteps
0.1603695314876302
1.0141959298740735
[-0.12514372 -1.615682    0.2546429   2.6574178 ]
854 Episode finished after 12 timesteps
0.16008108274323996
1.0168464809345703
[-0.16149479 -1.0137753   0.2464872   1.7266617 ]
855 Episode finished after 13 timesteps
0.15979315281733952
1.0111654150299727
[-0.12337876 -0.5969934   0.21904977  1.1725392 ]
856 Episode fi

0.14321740002167507
1.0167525698327355
[-0.06218494 -0.17989616  0.21705572  1.0263895 ]
915 Episode finished after 19 timesteps
0.1429169140272158
1.0221611132534842
[-0.12921669 -0.5722833   0.233655    1.1628007 ]
916 Episode finished after 13 timesteps
0.14261705848571019
1.018768263581608
[-0.22215012 -0.9644384   0.22614357  1.6360055 ]
917 Episode finished after 15 timesteps
0.14227513672477576
1.017570739345891
[-0.21358036 -1.368696    0.2420902   2.2199187 ]
918 Episode finished after 15 timesteps
0.14201923347329445
1.018757927697152
[-0.14681336 -0.9855212   0.21233913  1.7032167 ]
919 Episode finished after 13 timesteps
0.14180633240205523
1.0216643761377782
[-0.14832641 -1.7301875   0.21674323  2.7999938 ]
920 Episode finished after 9 timesteps
0.14159375049086936
1.0181597044691444
[-0.1800052 -1.0062777  0.2191964  1.6506445]
921 Episode finished after 11 timesteps
0.14138148726128394
1.0152143908457623
[-0.17578804 -1.198144    0.21126544  1.8652837 ]
922 Episode finis

0.1261844546029338
1.0177288012845176
[-0.10076792 -1.4089258   0.21286175  2.372758  ]
986 Episode finished after 15 timesteps
0.12603310138338888
1.0132391689611333
[-0.10735502 -1.6155608   0.21635923  2.544086  ]
987 Episode finished after 8 timesteps
0.12573093935299365
1.0161155248060822
[-0.17661554 -0.9672798   0.21068217  1.6292578 ]
988 Episode finished after 17 timesteps
0.12550479333104697
1.0121323854196818
[-0.15566078 -1.7464637   0.22395846  2.769222  ]
989 Episode finished after 11 timesteps
0.1253166490614832
1.0094879978336393
[-0.13015856 -1.4025586   0.22239292  2.3659947 ]
990 Episode finished after 11 timesteps
0.125091248202993
1.0122258740223267
[-0.12294494 -0.7859706   0.22312525  1.45145   ]
991 Episode finished after 12 timesteps
0.12482879288605007
1.0161092511455838
[-0.25431627 -2.180131    0.267815    3.295634  ]
992 Episode finished after 13 timesteps
0.1246416620089359
1.0217149150040414
[-0.09920648 -1.5912834   0.22082748  2.6026492 ]
993 Episode fi

0.11201433938281145
1.0130910739036543
[-0.10688835 -0.6118982   0.22958061  1.2387533 ]
1053 Episode finished after 15 timesteps
0.11184641865640337
1.014880784580277
[-0.1270123  -1.5613977   0.22681233  2.5697227 ]
1054 Episode finished after 10 timesteps
0.11167874966000156
1.0093873467994854
[-0.15141714 -1.7776558   0.2544434   2.889927  ]
1055 Episode finished after 9 timesteps
0.11151133201623753
1.0150294439867138
[-0.1671996  -1.3791043   0.21151225  2.197429  ]
1056 Episode finished after 11 timesteps
0.11127736887007436
1.0161128242034465
[-0.23729487 -1.3837823   0.23532939  2.0763302 ]
1057 Episode finished after 13 timesteps
0.11091070388033569
1.0103280183605172
[-0.1886955  -1.4157515   0.21991754  2.213292  ]
1058 Episode finished after 23 timesteps
0.11074443761420731
1.0218235332932737
[-0.12009206 -1.6097465   0.23535073  2.6116328 ]
1059 Episode finished after 10 timesteps
0.11044578619357145
1.0166332864318974
[-0.07783579 -0.22867253  0.21321288  0.78549373]
106

0.09994397608873219
1.0106896570034545
[-0.24510495 -1.221868    0.2370181   1.8709768 ]
1117 Episode finished after 18 timesteps
0.09973428253864197
1.0190082128780584
[-0.2517204  -2.1181993   0.26417726  3.2870893 ]
1118 Episode finished after 13 timesteps
0.09958477084876408
1.0163864153954718
[-0.21417676 -1.9393585   0.24665052  3.0400689 ]
1119 Episode finished after 10 timesteps
0.09943548329190086
1.0121753768374522
[-0.15423128 -1.9402975   0.2348913   3.0561106 ]
1120 Episode finished after 10 timesteps
0.09928641953205443
1.0167761266231536
[-0.13007018 -1.3886472   0.2342543   2.3644187 ]
1121 Episode finished after 11 timesteps
0.09913757923373062
1.0115154594079487
[-0.18135063 -0.7807326   0.23859082  1.4073558 ]
1122 Episode finished after 10 timesteps
0.09895926537331964
1.0164969587190584
[-0.18739831 -1.2103726   0.22513765  2.032012  ]
1123 Episode finished after 12 timesteps
0.09875163785555881
1.0150007134876573
[-0.18578352 -1.5871965   0.25285083  2.3690333 ]
1

0.08787281465414662
1.0202106180756043
[-0.16624092 -1.3690101   0.24151802  2.1804373 ]
1191 Episode finished after 13 timesteps
0.08768844773997772
1.0124644526125242
[-0.10240522 -1.025765    0.25036445  1.8502352 ]
1192 Episode finished after 13 timesteps
0.08753072686610912
1.0185076474974102
[-0.10947581 -0.7641031   0.21083204  1.4374348 ]
1193 Episode finished after 12 timesteps
0.08742573725100969
1.015801653265953
[-0.12802327 -1.3359135   0.22190875  2.1969967 ]
1194 Episode finished after 9 timesteps
0.08729467730469531
1.0098863122984767
[-0.14259543 -1.9576652   0.21133104  2.9571621 ]
1195 Episode finished after 10 timesteps
0.08711152338682684
1.0153071627331276
[-0.10856276 -0.99366575  0.24147482  1.8033571 ]
1196 Episode finished after 13 timesteps
0.08700703658957795
1.0138994231820107
[-0.15752557 -1.0029844   0.24233136  1.6903492 ]
1197 Episode finished after 9 timesteps
0.0867723992963415
1.009363470831886
[-0.11538061 -0.61500496  0.21270801  1.1648657 ]
1198 E

0.07663623118681605
1.0112047204324468
[-0.14443655 -0.75147504  0.21232218  1.5008935 ]
1271 Episode finished after 12 timesteps
0.07654430908468063
1.0205942650458641
[-0.13215296 -1.1909615   0.218597    1.9408917 ]
1272 Episode finished after 8 timesteps
0.07642956149026794
1.0093201361596584
[-0.14496823 -0.8072484   0.23680122  1.4665779 ]
1273 Episode finished after 10 timesteps
0.076314985914005
1.0125249566303358
[-0.15788546 -1.5225955   0.21271807  2.4373138 ]
1274 Episode finished after 10 timesteps
0.07620058209801936
1.0109811321728759
[-0.19070297 -1.2244918   0.23822366  2.0041847 ]
1275 Episode finished after 10 timesteps
0.0760635238798897
1.01035005311397
[-0.16527595 -1.1830294   0.24856591  1.9434627 ]
1276 Episode finished after 12 timesteps
0.07597228871732249
1.0155756088206545
[-0.1681667  -1.3788344   0.22835986  2.2381883 ]
1277 Episode finished after 9 timesteps
0.07581289042686953
1.0079825415741652
[-0.21268779 -0.9786565   0.23947333  1.6030781 ]
1278 Epi

0.06772473080964989
1.0135535603389143
[-0.15908957 -1.7721609   0.24928021  2.8608048 ]
1347 Episode finished after 11 timesteps
0.06760291768601599
1.0143732579255647
[-0.16512391 -0.36093885  0.22158071  0.8919223 ]
1348 Episode finished after 12 timesteps
0.06748132366162268
1.015322043870886
[-0.19354424 -1.3564049   0.2383645   2.2324638 ]
1349 Episode finished after 13 timesteps
0.06738016239110434
1.0105924711873133
[-0.09767194 -1.5965008   0.21275723  2.547381  ]
1350 Episode finished after 10 timesteps
0.06725896902564249
1.0159353073686361
[-0.14862013 -1.774651    0.24697943  2.844417  ]
1351 Episode finished after 11 timesteps
0.06711785224659945
1.010626960044297
[-0.05933471  0.00858106  0.22039431  0.44799256]
1352 Episode finished after 14 timesteps
0.06703734706029557
1.0107278626944338
[-0.16049959 -1.5998979   0.21047892  2.5373075 ]
1353 Episode finished after 8 timesteps
0.066876626260143
1.0122266282560304
[-0.1667273  -0.9961158   0.23300986  1.7084237 ]
1354 E

0.05986744777056833
1.010687498181748
[-0.08689967 -0.16787982  0.21807878  0.7052799 ]
1418 Episode finished after 13 timesteps
0.059741839223168655
1.008914872036817
[-0.11187074 -0.7542148   0.20959981  1.4525661 ]
1419 Episode finished after 14 timesteps
0.05965228021586134
1.0109556154347956
[-0.09582588 -0.74447304  0.22926036  1.4748769 ]
1420 Episode finished after 10 timesteps
0.05950926497692901
1.0191790511210759
[-0.18579295 -1.5895032   0.2123298   2.4277396 ]
1421 Episode finished after 16 timesteps
0.0594022286053505
1.0095735196955502
[-0.15013365 -0.98432255  0.23090798  1.710271  ]
1422 Episode finished after 13 timesteps
0.059295384754799514
1.0200564051893624
[-0.14847071 -1.1719      0.23621593  1.9325501 ]
1423 Episode finished after 12 timesteps
0.05920649502750625
1.0125665918975655
[-0.168126   -1.5805382   0.23793995  2.4561086 ]
1424 Episode finished after 10 timesteps
0.05910000323326073
1.0139075945131482
[-0.11311368 -1.0028285   0.22907913  1.7237211 ]
14

0.052969408607987184
1.0072121780598535
[-0.18836029 -1.7886195   0.25805232  2.865831  ]
1490 Episode finished after 11 timesteps
0.052905873915417984
1.0128180240946156
[-0.0661219 -1.551021   0.2152589  2.5062995]
1491 Episode finished after 8 timesteps
0.052826562705548946
1.007247876812471
[-0.13576014 -1.7358303   0.21629392  2.7621284 ]
1492 Episode finished after 9 timesteps
0.052763199350941314
1.0072887698188424
[-0.15438165 -1.7161468   0.23225513  2.8029907 ]
1493 Episode finished after 9 timesteps
0.05266829679394305
1.0148546655196697
[-0.14556478 -1.7767243   0.24130714  2.8085325 ]
1494 Episode finished after 11 timesteps
0.05255779286400011
1.0082900515900781
[-0.16419509 -1.5521525   0.23147342  2.6055849 ]
1495 Episode finished after 14 timesteps
0.05247900346252922
1.0127684202355642
[-0.15588713 -1.9839408   0.22259319  3.0395696 ]
1496 Episode finished after 10 timesteps
0.05240033217427134
1.0110686734318732
[-0.25839877 -2.1763065   0.26607445  3.2945054 ]
1497 

0.04520875605379436
1.021941417229495
[-0.16709007 -0.17940003  0.22157441  0.5427903 ]
1562 Episode finished after 15 timesteps
0.044857446944502034
1.012864942589373
[ 0.7439114   1.5361266  -0.22157216 -1.0124607 ]
1563 Episode finished after 52 timesteps
0.04479020113367785
1.0185467939823867
[-0.17448142 -1.3465449   0.23661749  2.2422376 ]
1564 Episode finished after 11 timesteps
0.04472305613106682
1.0324210352264345
[-0.15111011 -0.59401006  0.21221356  1.0836662 ]
1565 Episode finished after 9 timesteps
0.04436220865209388
1.0137118353698127
[ 0.29647228  0.55586207 -0.21255286 -0.56788844]
1566 Episode finished after 55 timesteps
0.04399107138517537
1.012651927072848
[ 0.67090034  1.7439337  -0.21609713 -1.5983839 ]
1567 Episode finished after 55 timesteps
0.0439119468208786
1.0148765019733796
[-0.23476942 -1.5999912   0.2638834   2.5387886 ]
1568 Episode finished after 12 timesteps
0.04384611840954499
1.0191487123258411
[-0.16538732 -1.3475751   0.25810125  2.2357605 ]
1569 

0.03360067890189606
1.0148242749273777
[-0.16807438 -0.19158612  0.21534137  0.57840997]
1626 Episode finished after 13 timesteps
0.0326956544082926
1.0135050300516455
[ 2.4003289   1.8461941   0.02589032 -0.40899873]
1627 Episode finished after 182 timesteps
0.03259769975658977
1.010280133641668
[-0.12590937  0.31379765  0.21053733  0.00754451]
1628 Episode finished after 20 timesteps
0.032470797311860644
1.0136932617239653
[-0.1079833  -0.02898473  0.21030964  0.32071134]
1629 Episode finished after 26 timesteps
0.03242212033084464
1.025072746599714
[-0.13568483 -0.4441922   0.22595231  0.8694503 ]
1630 Episode finished after 10 timesteps
0.03159620584959084
1.0129258948492639
[1.4908792  1.094231   0.21021383 0.27186555]
1631 Episode finished after 172 timesteps
0.031369496293273895
1.0138723002944856
[ 0.05289824 -1.21213     0.21965805  2.1095028 ]
1632 Episode finished after 48 timesteps
0.03060710814732839
1.0119980990062554
[2.4330885 1.9880186 0.1895498 0.4366179]
1633 Episode

0.014054119013399239
1.0103472645824887
[1.1762816  0.82378656 0.22210228 0.8024803 ]
1692 Episode finished after 133 timesteps
0.013811656513338667
1.009740259047881
[1.0954555  1.0307894  0.21566902 0.37652063]
1693 Episode finished after 116 timesteps
0.01354083507041773
1.0100417102194534
[1.6422071  1.2080308  0.21269484 0.8260622 ]
1694 Episode finished after 131 timesteps
0.013235551693260683
1.0111858258452757
[2.2189977  2.0206728  0.22317494 0.5077521 ]
1695 Episode finished after 153 timesteps
0.013050212325692178
1.009688622538385
[0.6876263  0.5499998  0.21016519 0.28819126]
1696 Episode finished after 93 timesteps
0.013030648748871705
1.0156096091493965
[-0.16756064 -0.25227463  0.21682966  0.5676775 ]
1697 Episode finished after 11 timesteps
0.012859748969511432
1.0120372978190697
[ 0.7002402  -0.22133216  0.22016886  1.4050189 ]
1698 Episode finished after 87 timesteps
0.012836618775084721
1.0036146396305412
[-0.11857546  0.19902888  0.21009922  0.05680952]
1699 Episode

In [6]:
play_dir = directory+'/'+'play'
os.mkdir(play_dir)
env = gym.make('CartPole-v0')
env = gym.wrappers.Monitor(env, play_dir, video_callable=lambda episode_id: True,force=True)

action=0
agent.epsilon = 0
scores = []
for i_episode in range(5):
    state = env.reset()
    score = 0
    
    #env is limited to 200 timesteps by default so range(>200 is fine)
    for t in range(1000):
        env.render()
        action = agent.getAction(state)
        n_state, reward, done, info = env.step(action)
        sleep(0.016) #Limit to 60 FPS
        state = n_state
        score += reward
        if done:
            scores.append(score)
            break
print(f' Mean score = {np.mean(score)}')
env.close()

 Mean score = 200.0


In [7]:
##USE THIS CELL TO SAVE TRAINED AGENT

import pickle
from datetime import datetime
dt = datetime.now()

with open(f'{train_dir}/RL-cart-{dt.strftime("%m%d%Y%H%M%S")}.pkl', 'wb') as outp:
    pickle.dump(agent, outp, pickle.HIGHEST_PROTOCOL)

with open(f'{train_dir}/RL-cart-progress{dt.strftime("%m%d%Y%H%M%S")}.pkl', 'wb') as outp:
    pickle.dump(progress, outp, pickle.HIGHEST_PROTOCOL)

