In [1]:
from DQNAgent import Experience, ExperienceReplay, Net, DQNAgent
import numpy as np
from time import sleep

In [2]:
from datetime import datetime
import os
dt = datetime.now()
directory = f"CartPole_results/result-{dt.strftime('%m-%d-%Y_%H-%M-%S')}"
os.mkdir(directory)

In [3]:
import gym
train_dir = directory+'/'+'training'
os.mkdir(directory+'/'+'training')
env = gym.make('CartPole-v0')
env = gym.wrappers.Monitor(env, train_dir, video_callable=lambda episode_id: episode_id % 200 == 0,force=True)
print(env.action_space)

Discrete(2)


C:\Users\mrida\anaconda3\lib\site-packages\gym\wrappers\monitor.py:31: UserWarning: The Monitor wrapper is being deprecated in favor of gym.wrappers.RecordVideo and gym.wrappers.RecordEpisodeStatistics (see https://github.com/openai/gym/issues/2297)
  warnings.warn(


In [4]:
#Change hyperparameters here
agent = DQNAgent(layerSizes=[4, 64, 2],
                epsilon=1, eps_decay=0.999,min_eps=0.01, batch_size=64, discount_fact=0.99, 
                 lr=0.0005, num_actions=2, target_update_freq=10000, mem_size = 65000,
                    update_freq = 2, start_training_after=1)

In [5]:
i_episode = 0
last_n_scores = [0]
n = 20
progress = []
running = []
done = False

while np.mean(last_n_scores) < 195:
    
    i_episode += 1
    state = env.reset()
    score = 0
    agent.loss_val = 0
    running = []
    
    for t in range(1000):
        action = agent.getAction(state)
        n_state, reward, done, info = env.step(action)
        score += reward
        agent.step(state, action, reward, n_state, int(done))
        running.append(action)
        state = n_state
        
        if done:
            print(agent.epsilon)
            print(agent.loss_val/t+1)
            print(n_state)
            print(f"{i_episode} Episode finished after {t+1} timesteps")
            if len(last_n_scores) == n:
                last_n_scores.pop(0)
            last_n_scores.append(score)
            if i_episode % 250 == 0:
                progress.append(running)
            break
progress.append(running)
env.close()

0.999
1.0
[-0.0303902  -0.04576578  0.21143357  0.6572061 ]
1 Episode finished after 20 timesteps
0.998001
1.0
[ 0.18164814  0.8329011  -0.21838902 -1.4898721 ]
2 Episode finished after 18 timesteps
0.997002999
1.0
[ 0.0277431  -0.01602516 -0.21251944 -0.5859476 ]
3 Episode finished after 22 timesteps
0.996005996001
1.4913637042045593
[ 0.15902989  0.5841972  -0.21794313 -1.1304897 ]
4 Episode finished after 21 timesteps
0.995009990004999
1.4898406598303053
[ 0.1585934   0.83659846 -0.23387201 -1.7800212 ]
5 Episode finished after 28 timesteps
0.994014980014994
1.4456937129680927
[ 0.07160469  0.43701535 -0.23213899 -1.046168  ]
6 Episode finished after 14 timesteps
0.993020965034979
1.353366868836539
[ 0.0040726   0.01919589 -0.21629512 -0.83904237]
7 Episode finished after 36 timesteps
0.9920279440699441
1.2989610487764531
[ 0.08513797  1.153168   -0.24331596 -2.1003213 ]
8 Episode finished after 12 timesteps
0.9910359161258742
1.2733318871921964
[ 0.13877138  1.547887   -0.2502646  

0.9323611649219127
1.0025815966073424
[-0.11683612 -1.576581    0.23932739  2.5855713 ]
70 Episode finished after 10 timesteps
0.9314288037569908
1.0030277361095483
[ 0.20369913  0.7517955  -0.21410708 -1.3287987 ]
71 Episode finished after 22 timesteps
0.9304973749532338
1.0035860531074419
[-0.1367051 -1.1369354  0.2376355  1.9420844]
72 Episode finished after 12 timesteps
0.9295668775782806
1.0024383602560394
[ 0.12149013  1.1470109  -0.22887567 -1.949901  ]
73 Episode finished after 10 timesteps
0.9286373107007023
1.0027091902059813
[ 0.13598633  0.4008273  -0.2187266  -0.9354171 ]
74 Episode finished after 10 timesteps
0.9277086733900016
1.0028061872192968
[-0.13862231 -0.642954    0.22111048  1.0819386 ]
75 Episode finished after 19 timesteps
0.9267809647166116
1.0045769732031558
[ 0.17784972  0.7996864  -0.21402384 -1.3412554 ]
76 Episode finished after 10 timesteps
0.925854183751895
1.0034501160594769
[-0.2093516  -1.0038575   0.24781445  1.7441423 ]
77 Episode finished after 15

0.8701675093639105
1.003820832150624
[-0.19855301 -0.45233977  0.23200217  1.0246714 ]
139 Episode finished after 24 timesteps
0.8692973418545467
1.0030062376797475
[-0.16592376 -1.5116298   0.21221462  2.1666417 ]
140 Episode finished after 28 timesteps
0.8684280445126921
1.0029805711563677
[-0.1747941  -1.2095729   0.21676828  1.9099593 ]
141 Episode finished after 26 timesteps
0.8675596164681794
1.001963654516398
[ 0.09921041  0.99420166 -0.2207635  -1.7584168 ]
142 Episode finished after 15 timesteps
0.8666920568517111
1.0023187042679638
[-0.12080267 -0.9848487   0.23568468  1.7493948 ]
143 Episode finished after 13 timesteps
0.8658253647948594
1.0026533058844507
[-0.11423845 -0.9411319   0.22823973  1.7281511 ]
144 Episode finished after 11 timesteps
0.8649595394300645
1.0029722757912665
[ 0.1636839   1.1718669  -0.21677753 -1.9598812 ]
145 Episode finished after 12 timesteps
0.8640945798906344
1.0027881473818394
[ 0.11714652  0.19984466 -0.21795279 -0.8702638 ]
146 Episode finish

0.8072619457390746
1.0025961463106796
[-0.13732615 -1.0168622   0.23572554  1.7866286 ]
214 Episode finished after 11 timesteps
0.8064546837933355
1.0030982499528263
[-0.08534454 -1.6127943   0.2319833   2.6311977 ]
215 Episode finished after 10 timesteps
0.8056482291095421
1.003692423691973
[ 0.13131195  0.97819376 -0.24047902 -1.7483132 ]
216 Episode finished after 19 timesteps
0.8048425808804326
1.0030898893665936
[ 0.18904857  1.5252079  -0.21506481 -2.4684908 ]
217 Episode finished after 10 timesteps
0.8040377382995522
1.0024596249092033
[-0.14500557 -1.2171186   0.23701982  2.1517732 ]
218 Episode finished after 12 timesteps
0.8032337005612527
1.0026842601509998
[-0.10967579 -0.6233422   0.21135865  1.1276413 ]
219 Episode finished after 17 timesteps
0.8024304668606914
1.0028929443409045
[ 0.12606613  1.5490831  -0.21090773 -2.4447532 ]
220 Episode finished after 10 timesteps
0.8016280363938307
1.0030005655538003
[-0.16279589 -1.2126541   0.23773937  2.0993927 ]
221 Episode finis

0.7511551214098489
1.003653650995917
[-0.18504292 -0.84393185  0.238674    1.5205054 ]
286 Episode finished after 14 timesteps
0.750403966288439
1.0032784217910375
[-0.17016359 -0.55386716  0.21212971  1.1839879 ]
287 Episode finished after 17 timesteps
0.7496535623221505
1.0023804395958515
[-0.16532129 -1.7338843   0.22461796  2.7436252 ]
288 Episode finished after 15 timesteps
0.7489039087598284
1.0024673984696468
[ 0.1364021  1.1339648 -0.2211292 -2.0090747]
289 Episode finished after 16 timesteps
0.7481550048510686
1.0023812398386116
[-0.08216351 -0.3873801   0.22078918  0.98147786]
290 Episode finished after 14 timesteps
0.7474068498462175
1.0032882179754476
[-0.17754392 -1.5850683   0.21812461  2.4812675 ]
291 Episode finished after 10 timesteps
0.7466594429963713
1.0029325522773433
[ 0.07600499  1.4101348  -0.21504341 -2.311717  ]
292 Episode finished after 17 timesteps
0.745912783553375
1.0021678728662664
[-0.1625019  -1.0247277   0.23488222  1.5782783 ]
293 Episode finished af

0.7017506636113059
1.002169270348862
[-0.15386307 -1.7798419   0.2432204   2.7589178 ]
354 Episode finished after 23 timesteps
0.7010489129476946
1.0026563748417954
[ 0.13088919  1.3832091  -0.2483158  -2.3330843 ]
355 Episode finished after 15 timesteps
0.7003478640347469
1.0028516481826573
[-0.17726481 -1.193041    0.23894076  2.0071857 ]
356 Episode finished after 20 timesteps
0.6996475161707122
1.0027209715917706
[-0.0746709  -0.6487241   0.22851458  1.404728  ]
357 Episode finished after 19 timesteps
0.6989478686545415
1.0027361066060383
[-0.14874993 -0.80099815  0.2307213   1.6218276 ]
358 Episode finished after 24 timesteps
0.698248920785887
1.0020864904350177
[-0.14109965 -0.8351463   0.23341359  1.4085999 ]
359 Episode finished after 12 timesteps
0.6975506718651011
1.0028825935053949
[-0.11296198 -0.9652118   0.2230838   1.7519405 ]
360 Episode finished after 13 timesteps
0.6968531211932361
1.0030068379581079
[-0.19285287 -1.7401478   0.23117311  2.5718668 ]
361 Episode finish

0.6536307811431531
1.0026381554198451
[-0.15995277 -1.0329095   0.23422433  1.8220059 ]
425 Episode finished after 15 timesteps
0.65297715036201
1.0027900223309796
[-0.13345502 -1.2210149   0.23637617  1.9984195 ]
426 Episode finished after 10 timesteps
0.6523241732116479
1.0028476764758427
[ 0.15442048  1.1749038  -0.22659908 -2.0601013 ]
427 Episode finished after 16 timesteps
0.6516718490384363
1.0039599652518518
[-0.12120725 -1.3960544   0.24643558  2.2644463 ]
428 Episode finished after 9 timesteps
0.6510201771893979
1.002456562490099
[-0.21593012 -1.5914322   0.21315676  2.464117  ]
429 Episode finished after 10 timesteps
0.6503691570122084
1.002575930540583
[ 0.16121516  1.912806   -0.23466367 -2.8420928 ]
430 Episode finished after 22 timesteps
0.6497187878551962
1.0035373119171709
[-0.14676188 -1.158786    0.21957815  1.8518409 ]
431 Episode finished after 12 timesteps
0.649069069067341
1.0038342744810507
[-0.15876333 -1.0321574   0.22315545  1.7908163 ]
432 Episode finished a

0.6051667933504074
1.0022059524516491
[-0.21174693 -1.5564754   0.21305737  2.0170717 ]
502 Episode finished after 34 timesteps
0.6045616265570569
1.0030959234766972
[-0.16153952 -1.7382624   0.22178254  2.7398047 ]
503 Episode finished after 13 timesteps
0.6039570649304998
1.0031117114915766
[-0.15844512 -1.2067689   0.21325274  1.9342233 ]
504 Episode finished after 12 timesteps
0.6033531078655693
1.0028257082449272
[-0.13375252 -1.7284027   0.24214615  2.8063118 ]
505 Episode finished after 13 timesteps
0.6027497547577038
1.0031575317056303
[ 0.19491072  1.5474297  -0.24676797 -2.5242772 ]
506 Episode finished after 18 timesteps
0.602147005002946
1.0027010650006367
[-0.10399539 -0.78560364  0.22063261  1.498129  ]
507 Episode finished after 20 timesteps
0.6015448579979431
1.0032797120511532
[-0.17060503 -1.0229038   0.21330202  1.5789332 ]
508 Episode finished after 11 timesteps
0.6009433131399452
1.002672872454342
[-0.16474995 -1.957852    0.25438765  3.094578  ]
509 Episode finish

0.5631061126214196
1.002662889737015
[-0.20576262 -1.5603088   0.24700329  2.4771457 ]
574 Episode finished after 10 timesteps
0.5625430065087982
1.0041253485251218
[-0.1632187  -0.94733596  0.2292744   1.6807201 ]
575 Episode finished after 9 timesteps
0.5619804635022894
1.002409556589555
[-0.11076289 -1.0129797   0.23017636  1.7670432 ]
576 Episode finished after 15 timesteps
0.561418483038787
1.0022984723909758
[-0.11931692 -1.4158417   0.21728657  2.256978  ]
577 Episode finished after 9 timesteps
0.5608570645557482
1.0024511979850517
[ 0.1466418   1.5608262  -0.21263117 -2.470374  ]
578 Episode finished after 12 timesteps
0.5602962074911925
1.0026197513440052
[-0.20495142 -0.42987397  0.21543135  0.8657442 ]
579 Episode finished after 14 timesteps
0.5597359112837013
1.0025483453646302
[-0.11658071 -1.3985002   0.20988208  2.2722077 ]
580 Episode finished after 11 timesteps
0.5591761753724176
1.0033261477947235
[-0.19829877 -1.5150404   0.21784267  2.4394479 ]
581 Episode finished 

0.5265964813194676
1.0384515032849528
[-0.13111708 -1.1786976   0.2329886   2.0017655 ]
641 Episode finished after 12 timesteps
0.5260698848381481
1.0232460852712393
[ 0.07715592  1.3469849  -0.2279593  -2.2698967 ]
642 Episode finished after 9 timesteps
0.5255438149533099
1.0369005519896746
[-0.08585569 -0.97209513  0.20993295  1.7800902 ]
643 Episode finished after 13 timesteps
0.5250182711383566
1.0304948360874102
[-0.13310306 -0.8248321   0.23488186  1.4306575 ]
644 Episode finished after 14 timesteps
0.5244932528672183
1.028610685840249
[-0.15840693 -0.9389672   0.2262018   1.6810018 ]
645 Episode finished after 9 timesteps
0.5239687596143511
1.0378480084240436
[-0.17733265 -0.92986006  0.21992421  1.559859  ]
646 Episode finished after 11 timesteps
0.5234447908547367
1.0279602491381494
[-0.12318632 -0.7898941   0.2334327   1.5325394 ]
647 Episode finished after 12 timesteps
0.522921346063882
1.0264522947371006
[-0.17714085 -1.0027405   0.24813214  1.791712  ]
648 Episode finished

0.4895066468838467
1.0198617367581888
[ 0.17375441  1.5914758  -0.21357736 -2.4051588 ]
714 Episode finished after 12 timesteps
0.48901714023696286
1.0269339116798206
[-0.16597584 -1.2066975   0.23902564  2.0790236 ]
715 Episode finished after 12 timesteps
0.4885281230967259
1.02481379515181
[ 0.21913972  0.954413   -0.22557247 -1.5877774 ]
716 Episode finished after 13 timesteps
0.48803959497362914
1.0263267944101244
[-0.15513845 -1.4138091   0.2456822   2.290717  ]
717 Episode finished after 9 timesteps
0.4875515553786555
1.0150570524856448
[-0.1530093  -1.3683467   0.21854277  2.136069  ]
718 Episode finished after 11 timesteps
0.48706400382327686
1.0247578744310886
[-0.07183196 -0.94764096  0.21196063  1.7309371 ]
719 Episode finished after 9 timesteps
0.4865769398194536
1.0270902283489705
[-0.10428987 -1.7151725   0.22639075  2.7930467 ]
720 Episode finished after 11 timesteps
0.48609036287963414
1.0327657088637352
[-0.25116307 -1.8017079   0.2527232   2.8186636 ]
721 Episode fini

0.4563969875256424
1.0268691930581222
[-0.1382764  -1.2232472   0.22838773  2.0460215 ]
784 Episode finished after 12 timesteps
0.45594059053811675
1.0211270971922204
[ 0.15825206  1.7953218  -0.22617705 -2.5735698 ]
785 Episode finished after 17 timesteps
0.45548464994757865
1.0264077650176153
[-0.1408855  -1.1499383   0.23173183  2.0506077 ]
786 Episode finished after 10 timesteps
0.45502916529763104
1.0273991200540746
[-0.18670486 -0.9882816   0.24002281  1.7423711 ]
787 Episode finished after 15 timesteps
0.45457413613233344
1.0308957722570216
[-0.0722852  -1.2035375   0.21852598  1.9801352 ]
788 Episode finished after 8 timesteps
0.4541195619962011
1.0220898007353147
[-0.20430407 -1.1929021   0.23135601  2.022557  ]
789 Episode finished after 16 timesteps
0.4536654424342049
1.0187624193107088
[-0.12400582 -0.57737535  0.20987077  1.1669455 ]
790 Episode finished after 13 timesteps
0.45321177699177073
1.0266273096203804
[-0.21930422 -1.208802    0.2384581   1.96141   ]
791 Episode 

0.42382727110771445
1.0244345095540797
[-0.20897675 -1.8105009   0.25446627  2.8165889 ]
858 Episode finished after 15 timesteps
0.4234034438366067
1.0247659269306395
[ 0.18801183  1.1665819  -0.22471797 -1.9572874 ]
859 Episode finished after 10 timesteps
0.4229800403927701
1.0295341699384153
[-0.11683835 -1.7801118   0.21932556  2.782792  ]
860 Episode finished after 9 timesteps
0.42255706035237733
1.024291706830263
[-0.13183574 -0.9422144   0.21493725  1.7957579 ]
861 Episode finished after 11 timesteps
0.42213450329202495
1.023493954539299
[-0.17667633 -1.3975751   0.21024378  2.2152305 ]
862 Episode finished after 11 timesteps
0.4217123687887329
1.0161611130461097
[-0.22765768 -1.8030529   0.24630107  2.7915514 ]
863 Episode finished after 13 timesteps
0.4212906564199442
1.021141855744645
[-0.14421175 -1.789267    0.22087935  2.772842  ]
864 Episode finished after 9 timesteps
0.42086936576352424
1.018037254922092
[-0.13204968 -0.9906984   0.23855205  1.7545135 ]
865 Episode finish

0.3943701631993207
1.0233952403068542
[-0.16487342 -1.7422404   0.21680899  2.7897918 ]
930 Episode finished after 11 timesteps
0.3939757930361214
1.024567906310161
[-0.13670984 -1.6139295   0.24220157  2.5967748 ]
931 Episode finished after 16 timesteps
0.3935818172430853
1.0176199760753661
[-0.05638925 -0.17501451  0.21467495  0.66174245]
932 Episode finished after 17 timesteps
0.3931882354258422
1.0227147288886564
[-0.15197551 -0.95022357  0.22562201  1.728386  ]
933 Episode finished after 15 timesteps
0.39279504719041636
1.0204423181712627
[-0.20543301 -1.9425577   0.21775442  2.9720862 ]
934 Episode finished after 10 timesteps
0.39240225214322594
1.01776788632075
[-0.15712687 -1.1663327   0.24323006  2.0521657 ]
935 Episode finished after 16 timesteps
0.39200984989108273
1.0242527125196323
[-0.15712088 -1.1472137   0.2406353   2.0659926 ]
936 Episode finished after 10 timesteps
0.39161784004119166
1.018769957125187
[-0.18719964 -1.5757885   0.2512254   2.508904  ]
937 Episode fini

0.3676954247709635
1.017694887239486
[-0.18062241 -0.58965635  0.22410862  1.0362092 ]
1000 Episode finished after 17 timesteps
0.36732772934619257
1.0191024445983417
[-0.1250848  -0.81924325  0.22346266  1.3430504 ]
1001 Episode finished after 18 timesteps
0.3669604016168464
1.024924959987402
[-0.13555302 -1.5781976   0.22901696  2.4911816 ]
1002 Episode finished after 10 timesteps
0.3665934412152296
1.0179150745272636
[ 0.2221194  1.3535733 -0.237509  -2.2116005]
1003 Episode finished after 11 timesteps
0.3662268477740143
1.015264632878825
[-0.1360102 -0.9427392  0.2484823  1.7421782]
1004 Episode finished after 9 timesteps
0.36586062092624033
1.0228780312463641
[-0.08302824 -1.3670554   0.23709811  2.3417292 ]
1005 Episode finished after 13 timesteps
0.3654947603053141
1.0205907615070993
[-0.18090045 -1.6114458   0.21642263  2.4748614 ]
1006 Episode finished after 12 timesteps
0.36512926554500874
1.0123777240514755
[-0.09746595 -1.7542734   0.21703503  2.8008285 ]
1007 Episode finis

0.34077312049111813
1.0208959430456161
[-0.1771625  -1.5229461   0.23915155  2.584201  ]
1076 Episode finished after 10 timesteps
0.340432347370627
1.0163058824837208
[-0.19621743 -1.9861134   0.25124237  3.1071944 ]
1077 Episode finished after 12 timesteps
0.34009191502325636
1.0240142145194113
[ 0.1810266   1.8022792  -0.23732731 -2.8353279 ]
1078 Episode finished after 9 timesteps
0.3397518231082331
1.0236431291620982
[-0.18377914 -1.5780594   0.22967944  2.3460324 ]
1079 Episode finished after 20 timesteps
0.33941207128512485
1.0209056507382128
[-0.09272242 -1.607881    0.22617234  2.580292  ]
1080 Episode finished after 10 timesteps
0.3390726592138397
1.0244833268225193
[-0.08139161 -1.5547973   0.21419914  2.5519097 ]
1081 Episode finished after 8 timesteps
0.3387335865546259
1.015216583555395
[ 0.18062441  1.1594757  -0.226817   -1.9748325 ]
1082 Episode finished after 12 timesteps
0.33839485296807126
1.0177863311361184
[-0.1359617  -1.171471    0.22966307  2.0225031 ]
1083 Epis

0.31677140557753575
1.0132716225149732
[-0.16321792 -1.3744493   0.24016684  2.2824442 ]
1149 Episode finished after 13 timesteps
0.31645463417195824
1.0199455018820507
[-0.1450314  -0.9764572   0.22347532  1.7622113 ]
1150 Episode finished after 15 timesteps
0.3161381795377863
1.0176175020635128
[-0.10789362 -1.33969     0.21516123  2.336172  ]
1151 Episode finished after 11 timesteps
0.3158220413582485
1.0183359675395947
[-0.17335701 -1.5840327   0.25053653  2.5389485 ]
1152 Episode finished after 14 timesteps
0.3155062193168902
1.0138438550962343
[-0.15017156 -1.5929435   0.22898108  2.5052004 ]
1153 Episode finished after 10 timesteps
0.31519071309757335
1.0176763976258891
[-0.14899822 -1.5422975   0.21804783  2.5275614 ]
1154 Episode finished after 8 timesteps
0.3148755223844758
1.0172424396643271
[-0.16392207 -1.55301     0.24829084  2.52037   ]
1155 Episode finished after 14 timesteps
0.31456064686209134
1.0160221665758977
[-0.16401774 -1.2105728   0.23396216  2.0095634 ]
1156 E

0.2965296975159237
1.0190749954093585
[-0.16478354 -1.5671299   0.23861122  2.5955544 ]
1215 Episode finished after 12 timesteps
0.29623316781840775
1.0188852325081825
[-0.0672845  -0.9941981   0.21401271  1.7209865 ]
1216 Episode finished after 9 timesteps
0.29593693465058934
1.0177841886878014
[-0.16207618 -1.0306721   0.2474253   1.7416712 ]
1217 Episode finished after 11 timesteps
0.29564099771593877
1.0151627784860986
[-0.09875246 -1.1705133   0.21396035  1.950075  ]
1218 Episode finished after 8 timesteps
0.2953453567182228
1.0160346077755094
[-0.11934085 -1.8077227   0.23705047  2.8563213 ]
1219 Episode finished after 9 timesteps
0.2950500113615046
1.0228290899346273
[-0.17723882 -1.4192194   0.25433856  2.2327263 ]
1220 Episode finished after 13 timesteps
0.2947549613501431
1.015270481551332
[-0.2079399  -2.1769829   0.24516088  3.2151787 ]
1221 Episode finished after 15 timesteps
0.294460206388793
1.016369555012456
[-0.13686448 -1.5498549   0.22171548  2.5540671 ]
1222 Episode

0.27454326105180193
1.0181698191624422
[-0.18570808 -1.6128625   0.22900382  2.5335348 ]
1292 Episode finished after 14 timesteps
0.2742687177907501
1.014331191778183
[-0.16602445 -1.1432946   0.23934042  2.008249  ]
1293 Episode finished after 10 timesteps
0.2739944490729594
1.01954708956182
[-0.17654066 -1.7800548   0.22345263  2.6808066 ]
1294 Episode finished after 11 timesteps
0.27372045462388644
1.017738432030786
[-0.12103593 -1.1852481   0.24226719  2.0070393 ]
1295 Episode finished after 12 timesteps
0.2734467341692626
1.0160033656284213
[-0.12387396 -1.7328968   0.21093379  2.7859385 ]
1296 Episode finished after 11 timesteps
0.27317328743509334
1.0141229160750906
[ 0.17317455  1.9874512  -0.26095182 -3.121217  ]
1297 Episode finished after 10 timesteps
0.27290011414765825
1.0185665525496006
[-0.07479481 -1.5563817   0.22618967  2.5924737 ]
1298 Episode finished after 8 timesteps
0.2726272140335106
1.0185939623889597
[-0.07355111 -1.5215362   0.23727623  2.5782387 ]
1299 Episo

0.2544414683340336
1.0142503708193544
[-0.09255718 -1.4060671   0.23813117  2.327667  ]
1368 Episode finished after 9 timesteps
0.25418702686569955
1.0108680633517604
[-0.21351711 -0.95306814  0.22409277  1.6516836 ]
1369 Episode finished after 13 timesteps
0.25393283983883386
1.0180555420617263
[-0.19608729 -1.9464328   0.21576078  3.0111206 ]
1370 Episode finished after 10 timesteps
0.25367890699899504
1.013505556517177
[-0.16591626 -1.5204818   0.21608327  2.390701  ]
1371 Episode finished after 10 timesteps
0.253425228091996
1.0135720560792834
[-0.13092034 -1.3338224   0.21868865  2.2453232 ]
1372 Episode finished after 9 timesteps
0.253171802863904
1.012869800574013
[-0.07612361 -1.5246018   0.22693792  2.5992594 ]
1373 Episode finished after 8 timesteps
0.2529186310610401
1.0135055429894815
[-0.17128576 -1.5769902   0.23996003  2.491355  ]
1374 Episode finished after 12 timesteps
0.2526657124299791
1.0140617859682866
[-0.14146182 -1.3938006   0.25594363  2.320734  ]
1375 Episode 

0.2362838408844548
1.0140140229836105
[-0.16268252 -1.0351857   0.22075322  1.7588667 ]
1442 Episode finished after 11 timesteps
0.23604755704357036
1.0223603493068367
[-0.1690088  -1.0241611   0.21567956  1.6457125 ]
1443 Episode finished after 9 timesteps
0.2358115094865268
1.0177000225944952
[-0.10745312 -1.6171527   0.2396054   2.6263797 ]
1444 Episode finished after 12 timesteps
0.23557569797704025
1.009458975517191
[-0.1148525 -1.3894421  0.2231013  2.2758253]
1445 Episode finished after 9 timesteps
0.2353401222790632
1.0128316171467304
[ 0.1259652   1.5370419  -0.25488836 -2.5126963 ]
1446 Episode finished after 10 timesteps
0.23510478215678413
1.0123995884787291
[-0.11200715 -1.7966143   0.22781955  2.819906  ]
1447 Episode finished after 9 timesteps
0.23486967737462733
1.0123673374099391
[-0.1045445  -1.5779494   0.21420887  2.5010388 ]
1448 Episode finished after 8 timesteps
0.2346348076972527
1.0205875218380243
[-0.14794466 -1.3915807   0.23896547  2.3184712 ]
1449 Episode f

0.22140669877912197
1.0224165555089713
[-0.1347188  -1.0315732   0.22213806  1.6361692 ]
1507 Episode finished after 11 timesteps
0.22118529208034285
1.0192728607604902
[-0.13518143 -1.5916487   0.21578275  2.4636395 ]
1508 Episode finished after 10 timesteps
0.2209641067882625
1.011580270016566
[-0.09030356 -0.6276303   0.23000538  1.164815  ]
1509 Episode finished after 9 timesteps
0.22074314268147424
1.0305100300659735
[-0.20212783 -0.99939734  0.2191684   1.5317578 ]
1510 Episode finished after 13 timesteps
0.22052239953879277
1.026874714427524
[-0.18462835 -0.7675281   0.22281314  1.3676822 ]
1511 Episode finished after 10 timesteps
0.22030187713925398
1.0236113724800258
[-0.17753305 -1.2204913   0.23299523  1.8881613 ]
1512 Episode finished after 14 timesteps
0.22008157526211472
1.0226907255128026
[-0.15414257 -0.97232527  0.22510071  1.6697139 ]
1513 Episode finished after 11 timesteps
0.2198614936868526
1.0344791926909238
[-0.09025984 -1.0173862   0.21023408  1.6567025 ]
1514 E

0.2060183520110343
1.0234005752612243
[-0.1417553  -0.4197047   0.21145731  0.739335  ]
1579 Episode finished after 12 timesteps
0.20581233365902327
1.0141552296467125
[-0.09361327 -0.5708136   0.23621324  1.2252929 ]
1580 Episode finished after 11 timesteps
0.20560652132536425
1.0171173471026123
[-0.13858223  0.12700894  0.21719705  0.31218553]
1581 Episode finished after 17 timesteps
0.20540091480403888
1.0203995596617461
[-0.12781946 -0.61779493  0.2226076   1.0424291 ]
1582 Episode finished after 11 timesteps
0.20519551388923485
1.0262910963967442
[-0.17002991 -1.382112    0.24275693  2.1739848 ]
1583 Episode finished after 11 timesteps
0.20499031837534562
1.027084237171544
[-0.12080304 -1.1979388   0.21514454  1.9431608 ]
1584 Episode finished after 10 timesteps
0.20478532805697028
1.0142944974359125
[-0.12677446 -0.64634556  0.23351157  1.1369197 ]
1585 Episode finished after 9 timesteps
0.2045805427289133
1.0296077232807874
[-0.14928263 -0.6061425   0.2094419   1.0318509 ]
1586 

0.1920835106763006
1.0161994132571495
[-0.11943853 -0.00756248  0.22176766  0.5040937 ]
1649 Episode finished after 14 timesteps
0.19189142716562432
1.0196641315706074
[ 0.27798617  2.483689   -0.23896737 -3.0958586 ]
1650 Episode finished after 25 timesteps
0.1916995357384587
1.025216677536567
[ 0.28419372  2.9007685  -0.22091992 -3.597498  ]
1651 Episode finished after 25 timesteps
0.19150783620272022
1.0210470465115375
[-0.11652005 -0.42561072  0.20964253  0.8524329 ]
1652 Episode finished after 10 timesteps
0.1913163283665175
1.017974798567593
[ 0.40485084  3.114811   -0.2360745  -3.6776137 ]
1653 Episode finished after 30 timesteps
0.19112501203815097
1.0185023218650242
[ 0.24091716  2.2601223  -0.21811557 -2.8317652 ]
1654 Episode finished after 30 timesteps
0.1909338870261128
1.018678675656422
[ 0.3054246   2.459135   -0.27728027 -3.2281222 ]
1655 Episode finished after 27 timesteps
0.19074295313908668
1.018742773267958
[-0.16519615 -0.61047536  0.22933616  1.0698545 ]
1656 Epis

0.17873320245609906
1.0134137796703726
[ 0.35764405  2.9155545  -0.23344249 -3.6516404 ]
1721 Episode finished after 25 timesteps
0.17855446925364296
1.01850653954898
[ 0.21672086  2.1281486  -0.2568303  -2.8925395 ]
1722 Episode finished after 33 timesteps
0.17837591478438933
1.0155549889637365
[ 0.31816342  2.6674552  -0.2128266  -3.334846  ]
1723 Episode finished after 28 timesteps
0.17819753886960493
1.0153726452383502
[ 0.3380988   2.724613   -0.25018856 -3.34699   ]
1724 Episode finished after 30 timesteps
0.17801934133073533
1.0197102635760198
[-0.12594973 -0.8085095   0.21280274  1.3590066 ]
1725 Episode finished after 12 timesteps
0.17784132198940458
1.0152637148992374
[-0.13830078 -0.06162245  0.20954442  0.45032862]
1726 Episode finished after 14 timesteps
0.1776634806674152
1.022082404870736
[-0.21616305 -0.06708767  0.21227574  0.40642992]
1727 Episode finished after 20 timesteps
0.17748581718674777
1.0145945569428687
[ 0.30028126  2.0828116  -0.25805864 -2.73333   ]
1728 

0.16647725295534047
1.016473446166716
[ 0.1809699   1.3377675  -0.24757971 -1.9651681 ]
1792 Episode finished after 27 timesteps
0.16631077570238512
1.016235986760316
[ 0.12280236  1.7452596  -0.25646335 -2.5438704 ]
1793 Episode finished after 27 timesteps
0.16614446492668272
1.0156029695644975
[ 0.30616364  2.3220623  -0.24229139 -2.8771806 ]
1794 Episode finished after 30 timesteps
0.16597832046175603
1.0163013351246202
[ 0.2543269   1.9519753  -0.24340424 -2.523357  ]
1795 Episode finished after 30 timesteps
0.16581234214129428
1.0196549416236256
[ 0.27757713  2.695677   -0.26375738 -3.6466124 ]
1796 Episode finished after 24 timesteps
0.16564652979915298
1.0160032571293414
[-0.09767525 -0.5690741   0.21243441  1.2343159 ]
1797 Episode finished after 13 timesteps
0.16548088326935384
1.0129144337514173
[ 0.20569569  2.667428   -0.21874304 -3.512628  ]
1798 Episode finished after 24 timesteps
0.1653154023860845
1.0183541647690748
[-0.21207383  0.13649528  0.212702    0.0098137 ]
1799

0.15568350913099022
1.0162337537516246
[-0.11396214 -0.00803554  0.21130393  0.3392237 ]
1859 Episode finished after 12 timesteps
0.15552782562185924
1.0173587119539402
[ 0.23892778  2.083855   -0.21046446 -2.6973865 ]
1860 Episode finished after 29 timesteps
0.15537229779623737
1.0128613570332528
[ 0.17394724  2.3105931  -0.23821564 -3.215419  ]
1861 Episode finished after 26 timesteps
0.15521692549844113
1.0113582257957507
[-0.11377582  0.18939811  0.21591634  0.12169795]
1862 Episode finished after 13 timesteps
0.15506170857294269
1.0186931270174682
[-0.148005   -1.0014123   0.23309655  1.6371429 ]
1863 Episode finished after 11 timesteps
0.15490664686436975
1.0200850655221276
[ 0.16704935  0.74878687 -0.22274752 -1.3884376 ]
1864 Episode finished after 10 timesteps
0.15475174021750537
1.0191138942415516
[-0.20847958 -0.22390407  0.21882373  0.5007662 ]
1865 Episode finished after 13 timesteps
0.15459698847728787
1.0212920431792736
[ 0.18628064  2.6737788  -0.243618   -3.6300278 ]
1

0.14486309656989407
1.0138280836611309
[ 0.1775125  2.1001534 -0.2168515 -2.8044188]
1931 Episode finished after 23 timesteps
0.1447182334733242
1.01194721841338
[-0.09502666 -0.03292021  0.21011667  0.4068747 ]
1932 Episode finished after 12 timesteps
0.14457351523985087
1.0221435401517038
[ 0.34358248  2.5110383  -0.21208535 -3.1725237 ]
1933 Episode finished after 27 timesteps
0.14442894172461102
1.0162945558317005
[-0.08853281 -0.19721813  0.21219538  0.60489655]
1934 Episode finished after 11 timesteps
0.1442845127828864
1.0205385721861744
[ 0.09982889  1.6997821  -0.2493319  -2.4361966 ]
1935 Episode finished after 27 timesteps
0.1441402282701035
1.0135051212051795
[ 0.26892227  2.3585322  -0.27114007 -3.1285806 ]
1936 Episode finished after 22 timesteps
0.1439960880418334
1.0198192360218277
[ 0.2016613  2.1333182 -0.213353  -2.8925793]
1937 Episode finished after 23 timesteps
0.14385209195379156
1.0172762305786212
[ 0.24113752  1.6871997  -0.22503681 -2.1312063 ]
1938 Episode fi

0.13574207980708144
1.0205764162167907
[ 0.16635107  1.1378727  -0.22940011 -1.5961665 ]
1996 Episode finished after 26 timesteps
0.13560633772727437
1.0242136961896904
[ 0.19456647  0.62872183 -0.23348139 -1.0139321 ]
1997 Episode finished after 17 timesteps
0.1354707313895471
1.0227140927778893
[ 0.48667747  1.9371496  -0.22964829 -2.1061978 ]
1998 Episode finished after 62 timesteps
0.13533526065815754
1.0176766748013704
[ 0.17621888  0.3633265  -0.2165281  -0.56956124]
1999 Episode finished after 24 timesteps
0.1351999253974994
1.0211207807296887
[ 0.17709453  0.62922823 -0.22446758 -0.9439418 ]
2000 Episode finished after 17 timesteps
0.13506472547210188
1.0246096216400877
[-0.22236939 -1.3261642   0.22813159  1.7124327 ]
2001 Episode finished after 37 timesteps
0.1349296607466298
1.0198971144855022
[ 0.23998179  0.99456865 -0.22253534 -1.2284211 ]
2002 Episode finished after 29 timesteps
0.13479473108588316
1.0222260950184945
[ 0.11711197  0.9931288  -0.22185843 -1.8196466 ]
2003

0.1269410862201967
1.0202781862534633
[ 0.11311451 -0.6631828   0.2258169   1.5098813 ]
2063 Episode finished after 147 timesteps
0.1268141451339765
1.0186798556500838
[ 0.23159947  2.10082    -0.24460763 -2.7802157 ]
2064 Episode finished after 55 timesteps
0.12668733098884255
1.0229481541833212
[ 0.26765087  0.42900082 -0.21397829 -0.35852778]
2065 Episode finished after 44 timesteps
0.12656064365785372
1.0184608781045037
[-0.06735602 -0.17610575  0.21674743  0.46795225]
2066 Episode finished after 43 timesteps
0.12643408301419587
1.0174798010033554
[-0.04814573 -0.55799735  0.21247636  0.7825701 ]
2067 Episode finished after 41 timesteps
0.12630764893118168
1.027129921040708
[0.13698639 0.5495815  0.21304087 0.02191635]
2068 Episode finished after 63 timesteps
0.1261813412822505
1.018925489078081
[-0.07661965 -0.4271246   0.23272434  1.0903965 ]
2069 Episode finished after 44 timesteps
0.12605515994096825
1.0279499485382233
[ 0.32151207 -0.22632967  0.21987633  1.2733697 ]
2070 Epis

0.11894849319464719
1.0230443052880998
[ 0.07197978  1.3619511  -0.24840711 -1.9560103 ]
2128 Episode finished after 57 timesteps
0.11882954470145254
1.0210528912210608
[ 0.86812735  2.9114323  -0.22554426 -3.0820687 ]
2129 Episode finished after 115 timesteps
0.11871071515675109
1.0208311002318036
[-0.08834228 -0.24050535  0.21556556  0.56037617]
2130 Episode finished after 35 timesteps
0.11859200444159435
1.0224151154635128
[ 0.2117515  -0.00247565 -0.2098259  -0.05652161]
2131 Episode finished after 28 timesteps
0.11847341243715274
1.0264506204026367
[0.4757401  0.52120376 0.21560788 0.3962755 ]
2132 Episode finished after 69 timesteps
0.1183549390247156
1.028112550881707
[ 0.2705232   0.7387683  -0.22850704 -0.7607605 ]
2133 Episode finished after 60 timesteps
0.11823658408569088
1.0214144611084948
[-0.16168994 -0.01021271  0.21250868  0.04327153]
2134 Episode finished after 50 timesteps
0.11811834750160519
1.0215252819274303
[ 0.05706923 -0.01720863  0.21383733  0.5927592 ]
2135 E

0.11145913789278664
1.0309135778167962
[1.4510405  0.6928387  0.22631629 0.88277143]
2193 Episode finished after 154 timesteps
0.11134767875489385
1.0362115679196564
[ 1.2453016   2.8403323  -0.23162048 -2.903053  ]
2194 Episode finished after 167 timesteps
0.11123633107613895
1.031638666243297
[ 0.5909305  -0.06024178  0.07301177  1.1461253 ]
2195 Episode finished after 200 timesteps
0.11112509474506281
1.032316726750948
[ 0.04999401 -0.01120208  0.21370655  0.54047114]
2196 Episode finished after 56 timesteps
0.11101396965031775
1.0341887450854605
[ 0.40992886  0.9227574  -0.21739708 -0.6836246 ]
2197 Episode finished after 121 timesteps
0.11090295568066744
1.0307539329683828
[-0.07997283 -0.25684857  0.21015798  0.7597132 ]
2198 Episode finished after 63 timesteps
0.11079205272498677
1.0342877155812136
[1.3179702  0.68289363 0.21114054 0.9048302 ]
2199 Episode finished after 146 timesteps
0.11068126067226178
1.0297728518267448
[ 0.90387094  1.062877    0.06712647 -0.09079413]
2200 E

0.10454588083304645
1.0426519149477826
[2.4274173  2.042545   0.10279104 0.03827411]
2257 Episode finished after 193 timesteps
0.1044413349522134
1.0411789775445308
[1.8410321  1.4716471  0.21214654 0.42048404]
2258 Episode finished after 160 timesteps
0.10433689361726119
1.0460206329767756
[2.4309165  1.9775423  0.10196903 0.05712079]
2259 Episode finished after 171 timesteps
0.10423255672364393
1.039383173842994
[ 1.7166227   1.7954779   0.10317846 -0.3511276 ]
2260 Episode finished after 200 timesteps
0.10412832416692028
1.043066619730477
[ 2.420247    2.0088046   0.11501908 -0.0414269 ]
2261 Episode finished after 193 timesteps
0.10402419584275335
1.0352719457135822
[ 2.411934    2.052953    0.0942071  -0.15762529]
2262 Episode finished after 197 timesteps
0.1039201716469106
1.0370188298332967
[2.4285948  1.7928406  0.09480908 0.20742427]
2263 Episode finished after 152 timesteps
0.10381625147526369
1.0274372244512155
[2.40608    1.8353266  0.10041555 0.1445339 ]
2264 Episode finis

In [6]:
play_dir = directory+'/'+'play'
os.mkdir(play_dir)
env = gym.make('CartPole-v0')
env = gym.wrappers.Monitor(env, play_dir, video_callable=lambda episode_id: True,force=True)

action=0
agent.epsilon = 0
scores = []
for i_episode in range(5):
    state = env.reset()
    score = 0
    
    #env is limited to 200 timesteps by default so range(>200 is fine)
    for t in range(1000):
        env.render()
        action = agent.getAction(state)
        n_state, reward, done, info = env.step(action)
        sleep(0.016) #Limit to 60 FPS
        state = n_state
        score += reward
        if done:
            scores.append(score)
            break
print(f' Mean score = {np.mean(score)}')
env.close()

 Mean score = 200.0


In [7]:
##USE THIS CELL TO SAVE TRAINED AGENT

import pickle
from datetime import datetime
dt = datetime.now()

with open(f'{train_dir}/RL-cart-{dt.strftime("%m%d%Y%H%M%S")}.pkl', 'wb') as outp:
    pickle.dump(agent, outp, pickle.HIGHEST_PROTOCOL)

with open(f'{train_dir}/RL-cart-progress{dt.strftime("%m%d%Y%H%M%S")}.pkl', 'wb') as outp:
    pickle.dump(progress, outp, pickle.HIGHEST_PROTOCOL)

